### ISSUE TITLE
pfSense support on FreeBSD

### ISSUE THREAD

**Issue by schniggie** [sshuttle/sshuttle#107]
Hey,

on pfSense 2.3.1 which is based on FreeBSD I get the follwoing error. Can someone help me out :) ?

```
[2.3.1-RELEASE][root@firewall.acme.corp]/root: sshuttle -l 0.0.0.0 -r user@server.tld 0/0
Enter passphrase for key '/root/.ssh/id_rsa':
client: Connected.
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sshuttle/cmdline.py", line 25, in main
    return firewall.main(opt.method, opt.syslog)
  File "/usr/local/lib/python2.7/site-packages/sshuttle/firewall.py", line 196, in main
    socket.AF_INET, subnets_v4, udp)
  File "/usr/local/lib/python2.7/site-packages/sshuttle/methods/pf.py", line 394, in setup_firewall
    pf.add_anchors()
  File "/usr/local/lib/python2.7/site-packages/sshuttle/methods/pf.py", line 159, in add_anchors
    self._add_anchor_rule(self.PF_RDR, b'sshuttle')
  File "/usr/local/lib/python2.7/site-packages/sshuttle/methods/pf.py", line 169, in _add_anchor_rule
    super(FreeBsd, self)._add_anchor_rule(type, name, pr=pr)
  File "/usr/local/lib/python2.7/site-packages/sshuttle/methods/pf.py", line 117, in _add_anchor_rule
    ioctl(pf_get_dev(), pf.DIOCCHANGERULE, pr)
**IOError: [Errno 19] Operation not supported by device**
client: fatal: cleanup: ['/usr/local/bin/python2.7', '/usr/local/bin/sshuttle', '--method', 'auto', '--firewall'] returned 1
```

**Comment by vieira** [comment]
Hello @schniggie 

Although pfSense is FreeBSD based, they have their own version/fork of pf with different ioctls. A quick look around did not return much documentation so adding support would involve a lot of trial and error. #100 also turned out to be someone using pfSense and hitting this problem so I might give another look at this.

**Comment by schniggie** [comment]
Would be really cool. Thanks for you help.
