### ISSUE TITLE
FreeBSD and jail

### ISSUE THREAD

**Issue by mrPsycho** [sshuttle/sshuttle#125]
Hello,

just tried this utility to make simple VPN, and have this:

`root@staff:/projects/Addons/sshuttle # sshuttle -vvv -r username@server:port 0.0.0.0/0
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.12
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: False
Binding redirector: 12300Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==0.78.2.dev16+ng0e52cce.d20161207', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python2.7/site-packages/sshuttle-0.78.2.dev16+ng0e52cce.d20161207-py2.7.egg/sshuttle/cmdline.py", line 74, in main
    opt.daemon, opt.pidfile)
  File "/usr/local/lib/python2.7/site-packages/sshuttle-0.78.2.dev16+ng0e52cce.d20161207-py2.7.egg/sshuttle/client.py", line 639, in main
    raise e
socket.error: [Errno 43] Protocol not supported
`

what is wrong?

tried different servers, but none works.

**Comment by vieira** [comment]
Hello @mrPsycho 

I have tested right now with HEAD and was unable to reproduce this problem. I am using FreeBSD 11.0-RELEASE-p1 (a droplet from digital ocean). Same version of Python as you (2.7.12).

Below are the steps I used. Are you doing something different? Do these steps work for you?

```
root@fbsd:~ # uname -a
FreeBSD fbsd 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
root@fbsd:~ # git clone https://github.com/sshuttle/sshuttle.git
root@fbsd:~ # cd sshuttle
root@fbsd:~/sshuttle #  kldload pf
root@fbsd:~/sshuttle # ./run -vvv -r user@myserver 0.0.0.0/0
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.12
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: False
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket._socketobject object at 0x8018bdec0>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket._socketobject object at 0x80191d2f0>.
Starting client with Python version 2.7.12
c : connecting to server...
c : executing: ['ssh', 'user@myserver', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(978), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling u'sshuttle' (7 bytes)
server: assembling u'sshuttle.cmdline_options' (44 bytes)
server: assembling u'sshuttle.helpers' (950 bytes)
server: assembling u'sshuttle.ssnet' (5625 bytes)
server: assembling u'sshuttle.hostwatch' (2368 bytes)
server: assembling u'sshuttle.server' (3302 bytes)
Starting server with Python version 2.7.9
 s: latency control setting = True
 s: available routes:
 s:   2/10.5.192.0/24
 s:   2/193.136.128.64/26
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=36 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=43/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=43/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 44/44
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=43/0)
c : Connected.
c : Waiting: 2 r=[4, 7, 10] w=[10] x=[] (fullness=7/0)
c :   Ready: 2 r=[10] w=[10] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=36
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0'), (2, 32, True, '127.0.0.1'), (28, 128, True, '::1')]
firewall manager: Got nslist: []
firewall manager: Got ports: 12300,12300,0,0
firewall manager: Got udp: False
firewall manager: setting up.
firewall manager: setting up IPv6.
>> pfctl -s all
rules:
---> table <forward_subnets> {!::1/128}
---> rdr pass on lo0 inet6 proto tcp to <forward_subnets> -> ::1 port 12300
---> pass out route-to lo0 inet6 proto tcp to <forward_subnets> keep state
>> pfctl -a sshuttle6-12300 -f /dev/stdin
firewall manager: setting up IPv4.
>> pfctl -s all
rules:
---> table <forward_subnets> {!127.0.0.1/32,0.0.0.0/0}
---> rdr pass on lo0 inet proto tcp to <forward_subnets> -> 127.0.0.1 port 12300
---> pass out route-to lo0 inet proto tcp to <forward_subnets> keep state
>> pfctl -a sshuttle-12300 -f /dev/stdin
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 2 r=[4, 7, 10] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
c :   Ready: 2 r=[10] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 2 r=[4, 7, 10] w=[] x=[] (fullness=0/0)
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=43)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c :   Ready: 2 r=[7] w=[] x=[]
c : QUERY_PF_NAT 2,6,46.101.147.112,21447,127.0.0.1,12300
--->  > QUERY_PF_NAT_SUCCESS 188.113.88.193,80
c : Accept TCP: 46.101.147.112:21447 -> 188.113.88.193:80.
c :  > channel=1 cmd=TCP_CONNECT len=19 (fullness=0)
c : creating new SockWrapper (1 now exist)
c : new channel: 1
c : creating new SockWrapper (2 now exist)
c : Remaining DNS requests: 0
c : Remaining UDP channels: 0
c : Waiting: 3 r=[4, 7, 8, 10] w=[10] x=[] (fullness=19/0)
c :   Ready: 3 r=[] w=[10] x=[]
c : mux wrote: 27/27
(...)
```

**Comment by brianmay** [comment]
No response. Closing.
