### ISSUE TITLE
Cannot handle link-local IPv6 addresses with scope

### ISSUE THREAD

**Issue by fkoester** [sshuttle/sshuttle#156]
I use the same sshuttle command successfully for a long time now, but suddenly `--dns` does not work properly on my system anymore. I start it with the following command:

```sh
sshuttle -v --dns -r <domain>:3633 192.168.1.1/24 192.168.178.1 192.168.177.1
```

And it starts up just fine:

```sh
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.12
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12300).
Starting client with Python version 2.7.12
c : connecting to server...
Starting server with Python version 2.7.12
 s: latency control setting = True
 s: available routes:
 s:   2/172.17.0.0/16
 s:   2/172.18.0.0/16
 s:   2/172.19.0.0/16
 s:   2/172.20.0.0/16
 s:   2/172.21.0.0/16
 s:   2/192.168.1.0/24
 s:   2/192.168.1.1/32
 s:   2/192.168.122.0/24
c : Connected.
firewall manager: setting up.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.178.1/32 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.177.1/32 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.1.1/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.178.1/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
```

But when I now try to connect via ssh to a domainname, it crashes:

```sh
c : DNS request from ('192.168.178.88', 49760) to None: 38 bytes
c : DNS request from ('192.168.178.88', 49760) to None: 38 bytes
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 37, in <module>
  File "sshuttle.server", line 345, in main
  File "sshuttle.ssnet", line 585, in runonce
  File "sshuttle.ssnet", line 483, in callback
  File "sshuttle.ssnet", line 471, in handle
  File "sshuttle.ssnet", line 405, in got_packet
  File "sshuttle.server", line 304, in dns_req
  File "sshuttle.server", line 140, in __init__
  File "sshuttle.server", line 151, in try_send
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 22] Invalid argument
firewall manager: undoing changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
c : fatal: server died with error code 1
```

I use sshuttle in version 0.78.1 from Gentoo packages.

sshuttle is really, really helpful. Thanks for your great work!

**Comment by brianmay** [comment]
Fabian Köster <notifications@github.com> writes:

>   File "/usr/lib64/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> socket.error: [Errno 22] Invalid argument

This is a problem with the server you are connecting to. What is the
contents of /etc/resolv.conf on the server?
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by fkoester** [comment]
I would like to provide more information:

1. I did not make any changes to the target system lately and especially I did not change the nameserver configuration.
2. I did not change the sshuttle version on the client, other parts of the client installation might have changed though.
3. The problem also occurs with the latest git version (`f9361d7`) of sshuttle.
4. I examined the failing code and move the line `debug2('DNS: sending to %r (try %d)\n' % (peer, self.tries))` before `sock.connect((peer, 53))` in `server.py` and this is the output:

```
fabian@hamilton ~/workspace/sshuttle $ ./run -vvv --dns -r <domain>:3633 192.168.1.1/24 192.168.178.1 192.168.177.1
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.12
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket._socketobject object at 0x7fa1e26db1a0>.
Binding DNS: 12300
DNS listening on ('127.0.0.1', 12300).
DNS listening with <socket._socketobject object at 0x7fa1e26db210>.
Starting client with Python version 2.7.12
c : connecting to server...
c : executing: ['ssh', '-p', '3633', 'gate.ek-beratung.eu', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(978), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling u'sshuttle' (7 bytes)
server: assembling u'sshuttle.cmdline_options' (44 bytes)
server: assembling u'sshuttle.helpers' (950 bytes)
server: assembling u'sshuttle.ssnet' (5625 bytes)
server: assembling u'sshuttle.hostwatch' (2368 bytes)
server: assembling u'sshuttle.server' (3574 bytes)
Starting server with Python version 2.7.12
 s: latency control setting = True
 s: available routes:
 s:   2/172.17.0.0/16
 s:   2/172.18.0.0/16
 s:   2/172.19.0.0/16
 s:   2/172.20.0.0/16
 s:   2/172.21.0.0/16
 s:   2/192.168.1.0/24
 s:   2/192.168.122.0/24
c : Connected.
c : Waiting: 3 r=[4, 7, 10] w=[10] x=[] (fullness=7/0)
c :   Ready: 3 r=[] w=[10] x=[]
c : mux wrote: 15/15
 s:  > channel=0 cmd=PING len=7 (fullness=0)
c : Waiting: 3 r=[4, 7, 10] w=[] x=[] (fullness=7/0)
 s:  > channel=0 cmd=ROUTES len=116 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=123/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=123/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 124/124
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=123/0)
c :   Ready: 3 r=[10] w=[] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=116
firewall manager: Got subnets: [(2, 24, False, '192.168.1.1', 0, 0), (2, 32, False, '192.168.178.1', 0, 0), (2, 32, False, '192.168.177.1', 0, 0), (2, 32, True, '127.0.0.1', 0, 0)]
firewall manager: Got partial nslist: [(2, '192.168.178.1')]
firewall manager: Got nslist: [(2, '192.168.178.1')]
firewall manager: Got ports: 0,12300,0,12300
firewall manager: Got udp: False
firewall manager: setting up.
firewall manager: setting up IPv4.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.178.1/32 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.177.1/32 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.1.1/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.178.1/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
c : mux wrote: 15/15
c : Waiting: 3 r=[4, 7, 10] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=123)
 s: mux wrote: 15/15
c :   Ready: 3 r=[10] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 3 r=[4, 7, 10] w=[] x=[] (fullness=0/0)
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=130/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c :   Ready: 3 r=[7] w=[] x=[]
c : Accept UDP using recvfrom.
c : DNS request from ('192.168.178.88', 44804) to None: 37 bytes
c :  > channel=1 cmd=DNS_REQ len=37 (fullness=0)
c : Remaining DNS requests: 1
c : Remaining UDP channels: 0
c : Waiting: 3 r=[4, 7, 10] w=[10] x=[] (fullness=37/0)
c :   Ready: 3 r=[7] w=[10] x=[]
c : mux wrote: 45/45
c : Accept UDP using recvfrom.
c : DNS request from ('192.168.178.88', 44804) to None: 37 bytes
c :  > channel=2 cmd=DNS_REQ len=37 (fullness=37)
c : Remaining DNS requests: 2
c : Remaining UDP channels: 0
c : Waiting: 3 r=[4, 7, 10] w=[10] x=[] (fullness=74/0)
c :   Ready: 3 r=[] w=[10] x=[]
c : mux wrote: 45/45
c : Waiting: 3 r=[4, 7, 10] w=[] x=[] (fullness=74/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=1 cmd=DNS_REQ len=37
 s: Incoming DNS request channel=1.
 s: DNS: sending to '192.168.1.1' (try 1)
 s: DNS: sending to '192.168.1.1' (try 1)
 s: Waiting: 2 r=[4, 6] w=[] x=[] (fullness=0/0)
 s:   Ready: 2 r=[4] w=[] x=[]
 s: <  channel=2 cmd=DNS_REQ len=37
 s: Incoming DNS request channel=2.
 s: DNS: sending to '192.168.1.1' (try 1)
 s: DNS: sending to '192.168.1.1' (try 1)
 s: Waiting: 3 r=[4, 6, 8] w=[] x=[] (fullness=0/0)
 s:   Ready: 3 r=[6] w=[] x=[]
 s: DNS response: 117 bytes
 s:  > channel=1 cmd=DNS_RESPONSE len=117 (fullness=0)
 s: expiring dnsreqs channel=1
 s: Waiting: 2 r=[4, 8] w=[5] x=[] (fullness=117/0)
 s:   Ready: 2 r=[8] w=[5] x=[]
 s: mux wrote: 125/125
 s: DNS response: 129 bytes
 s:  > channel=2 cmd=DNS_RESPONSE len=129 (fullness=117)
 s: expiring dnsreqs channel=2
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=246/0)
 s:   Ready: 1 r=[] w=[5] x=[]
c :   Ready: 3 r=[10] w=[] x=[]
c : <  channel=1 cmd=DNS_RESPONSE len=117
c : dns_done: channel=1 src=None dst=('192.168.178.88', 44804)
 s: mux wrote: 137/137
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=246/0)
c : <  channel=2 cmd=DNS_RESPONSE len=129
c : dns_done: channel=2 src=None dst=('192.168.178.88', 44804)
c : Waiting: 3 r=[4, 7, 10] w=[] x=[] (fullness=74/0)
c :   Ready: 3 r=[7] w=[] x=[]
c : Accept UDP using recvfrom.
c : DNS request from ('192.168.178.88', 52287) to None: 34 bytes
c :  > channel=3 cmd=DNS_REQ len=34 (fullness=74)
c : Remaining DNS requests: 1
c : Remaining UDP channels: 0
c : Waiting: 3 r=[4, 7, 10] w=[10] x=[] (fullness=108/0)
c :   Ready: 3 r=[7] w=[10] x=[]
c : mux wrote: 42/42
c : Accept UDP using recvfrom.
c : DNS request from ('192.168.178.88', 52287) to None: 34 bytes
c :  > channel=4 cmd=DNS_REQ len=34 (fullness=108)
c : Remaining DNS requests: 2
c : Remaining UDP channels: 0
c : Waiting: 3 r=[4, 7, 10] w=[10] x=[] (fullness=142/0)
c :   Ready: 3 r=[] w=[10] x=[]
c : mux wrote: 42/42
c : Waiting: 3 r=[4, 7, 10] w=[] x=[] (fullness=142/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=3 cmd=DNS_REQ len=34
 s: Incoming DNS request channel=3.
 s: DNS: sending to 'fe80::1ad6:c7ff:fe61:8043%2' (try 1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 37, in <module>
  File "sshuttle.server", line 377, in main
  File "sshuttle.ssnet", line 595, in runonce
  File "sshuttle.ssnet", line 483, in callback
  File "sshuttle.ssnet", line 471, in handle
  File "sshuttle.ssnet", line 405, in got_packet
  File "sshuttle.server", line 336, in dns_req
  File "sshuttle.server", line 171, in __init__
  File "sshuttle.server", line 183, in try_send
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 22] Invalid argument
c :   Ready: 3 r=[10] w=[] x=[]
firewall manager: undoing IPv4 changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
firewall manager: undoing /etc/hosts changes.
c : fatal: server died with error code 1
```

As you can see it tries to send a DNS request to `fe80::1ad6:c7ff:fe61:8043%2` which does not seem right to me, why the `%2` at the end?

**Comment by fkoester** [comment]
Oh, I just recognize I stated wrong information about the server! I was mistakenly assuming I was using a different gateway, sorry! The correct answers to your questions are:

> This is a problem with the server you are connecting to. What is the contents of /etc/resolv.conf on the server?

```
heisenberg ~ # cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
[ ...]
nameserver 192.168.1.1
nameserver fe80::1ad6:c7ff:fe61:8043%2
```

So this clears up the mysterious address `fe80::1ad6:c7ff:fe61:8043%2` I saw in the debug output! I guess this is due to a recent update of systemd on the target machine and it does not seem to be a bug in sshuttle. Nevertheless, thanks for hour help!

**Comment by brianmay** [comment]
Glad you resolved it.

Strange, that doesn't look like a valid IPv6 address to me.

Ideally we would be more robust in case of problems in ``/etc/resolv.conf`` however I don't have time to look at this now.

**Comment by fkoester** [comment]
I think I need to reopen this issue. I just learned the address given above `fe80::1ad6:c7ff:fe61:8043%2` seems to actually be a valid (link-local) IPv6 address according to https://superuser.com/questions/99746/why-is-there-a-percent-sign-in-the-ipv6-address.

And it is also reachable:

```bash
fabian@heisenberg ~ $ ping6 'fe80::1ad6:c7ff:fe61:8043%2'
PING fe80::1ad6:c7ff:fe61:8043%2(fe80::1ad6:c7ff:fe61:8043) 56 data bytes
64 bytes from fe80::1ad6:c7ff:fe61:8043: icmp_seq=1 ttl=64 time=0.167 ms
```

So i guess sshuttle (or the address parsing library) should learn to handle those kind of addresses.

**Comment by brianmay** [comment]
Fabian Köster <notifications@github.com> writes:

> I think I need to reopen this issue. I just learned the address given
> above `fe80::1ad6:c7ff:fe61:8043%2` seems to actually be a valid
> (link-local) IPv6 address according to
> https://superuser.com/questions/99746/why-is-there-a-percent-sign-in-the-ipv6-address.

Agreed. Thanks for looking into this.

> So i guess sshuttle (or the address parsing library) should learn to
> handle those kind of addresses.

Patches to fix the welcome.

Actually I suspect this is going to have to be system dependant. We need
to look up the interface associated with %2 and bind to it. Yuck.

I welcome being proved wrong on the above :-)
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by fkoester** [comment]
> Patches to fix the welcome.

Will see what I can do :-)

> Actually I suspect this is going to have to be system dependant. We need to look up the interface associated with %2 and bind to it. Yuck.

Aren't there any libraries to help with that? I will do some research!
