### ISSUE TITLE
OSX 10.10 + sshuttle + tproxy throws socket.error: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by Saren-Arterius** [sshuttle/sshuttle#20]
sshuttle is installed through brew.
```
$ sshuttle --dns -r server 0/0 -v --method=tproxy
Starting sshuttle proxy.
tproxy UDP support requires recvmsg function.
tproxy DNS support requires recvmsg function.
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening on ('127.0.0.1', 12300).
firewall manager ready method tproxy.
Traceback (most recent call last):
  File "/usr/local/Cellar/sshuttle/0.71/libexec/src/main.py", line 216, in <module>
    opt.syslog, opt.daemon, opt.pidfile)
  File "/usr/local/Cellar/sshuttle/0.71/libexec/src/client.py", line 743, in main
    tcp_listener.setsockopt(socket.SOL_IP, IP_TRANSPARENT, 1)
  File "/usr/local/Cellar/sshuttle/0.71/libexec/src/client.py", line 228, in setsockopt
    self.v6.setsockopt(level, optname, value)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 22] Invalid argument
```
How do I obtain the `recvmsg` function?

**Comment by brianmay** [comment]
I believe tproxy is a Linux only kernel interface that is not supported with Mac OS X.

http://www.mjmwired.net/kernel/Documentation/networking/tproxy.txt

It looks wrong that it assumes you have IPv6 support, and it looks like this is causing the failure, however what you are attempting isn't going to work anyway.

**Comment by Saren-Arterius** [comment]
I see. It seems that it's nearly impossible (or at least very difficult to setup) for OS X to proxy UDP traffic without using actual VPN. Thanks anyway.
