### ISSUE TITLE
Error when execuing sshuttle

### ISSUE THREAD

**Issue by manuelbuil** [sshuttle/sshuttle#206]
sshuttle -r user@server 192.168.122.0/24
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/sshuttle/cmdline.py", line 76, in main
    opt.daemon, opt.pidfile)
  File "/usr/lib/python3.4/site-packages/sshuttle/client.py", line 744, in main
    seed_hosts, auto_hosts, auto_nets, daemon)
  File "/usr/lib/python3.4/site-packages/sshuttle/client.py", line 437, in _main
    auto_hosts=auto_hosts))
  File "/usr/lib/python3.4/site-packages/sshuttle/ssh.py", line 96, in connect
    empackage(z, 'sshuttle.server') +
  File "/usr/lib/python3.4/site-packages/sshuttle/ssh.py", line 60, in empackage
    return b'%s\n%d\n%s' % (name.encode("ASCII"), len(content), content)
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

Note that I am using Linux and:
sshuttle==0.78.3

**Comment by brianmay** [comment]
This is because we don't support Python 3.4 on the client side. Sorry.
