### ISSUE TITLE
No module named 'zlib'

### ISSUE THREAD

**Issue by ssabetan** [sshuttle/sshuttle#255]
I've recenrtly encountered an error with sshuttle on Ubuntu 16.04 and two separate installs of Mac OS X Sierra. 

Here is the error I'm receiving:

```user@hostname:~/sshuttle$ ./run -vr user@host 10.0.0.0/24
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.5.2
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 3.5.2
c : connecting to server...
user@host's password: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 2, in <module>
ModuleNotFoundError: No module named 'zlib'
c : fatal: server died with error code 1
```

I have verified that zlib is installed on both Ubuntu and Mac (see below). I have also verified that zlib is installed on pip. I've even tried installing using apt-get install sshuttle and brew install sshuttle. 
```
user@hostname:~/sshuttle$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>> 
user@hostname::~/sshuttle$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>> 
```

Any ideas?

**Comment by brianmay** [comment]
This puzzles me because normally zlib is compiled into python. This error is from the server BTW. e.g.

```
brian@silverfish:~$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>> zlib
<module 'zlib' (built-in)>
>>> 
brian@silverfish:~$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>> zlib
<module 'zlib' (built-in)>
>>> 
```

**Comment by ssabetan** [comment]
Just checked that the server has python and zlib and it does:

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>> zlib
<module 'zlib' (built-in)>
>>> 
```

Any other suggestions of things to do on the box?

**Comment by ssabetan** [comment]
Resolved. The server got upgraded to python 3.7 -- which doesn't _seem_ to have zlib by default.
