### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by brianjmurrell** [sshuttle/sshuttle#275]
If I interrupt (`^C` aka SIGINTR) sshuttle and then try to restart it right away, I will typically get the following for some time before I can restart sshuttle:

```
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.6.5
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
Binding redirector: 12300 12299 12298 12297 12296 12295 12294 12293 12292 12291 12290 12289 12288 12287 12286 12285 12284 12283 12282 12281 12280 12279 12278 12277 12276 12275 12274 12273 12272 12271 12270 12269 12268 12267 12266 12265 12264 12263 12262 12261 12260 12259 12258 12257 12256 12255 12254 12253 12252 12251 12250 12249 12248 12247 12246 12245 12244 12243 12242 12241 12240 12239 12238 12237 12236 12235 12234 12233 12232 12231 12230 12229 12228 12227 12226 12225 12224 12223 12222 12221 12220 12219 12218 12217 12216 12215 12214 12213 12212 12211 12210 12209 12208 12207 12206 12205 12204 12203 12202 12201 12200 12199 12198 12197 12196 12195 12194 12193 12192 12191 12190 12189 12188 12187 12186 12185 12184 12183 12182 12181 12180 12179 12178 12177 12176 12175 12174 12173 12172 12171 12170 12169 12168 12167 12166 12165 12164 12163 12162 12161 12160 12159 12158 12157 12156 12155 12154 12153 12152 12151 12150 12149 12148 12147 12146 12145 12144 12143 12142 12141 12140 12139 12138 12137 12136 12135 12134 12133 12132 12131 12130 12129 12128 12127 12126 12125 12124 12123 12122 12121 12120 12119 12118 12117 12116 12115 12114 12113 12112 12111 12110 12109 12108 12107 12106 12105 12104 12103 12102 12101 12100 12099 12098 12097 12096 12095 12094 12093 12092 12091 12090 12089 12088 12087 12086 12085 12084 12083 12082 12081 12080 12079 12078 12077 12076 12075 12074 12073 12072 12071 12070 12069 12068 12067 12066 12065 12064 12063 12062 12061 12060 12059 12058 12057 12056 12055 12054 12053 12052 12051 12050 12049 12048 12047 12046 12045 12044 12043 12042 12041 12040 12039 12038 12037 12036 12035 12034 12033 12032 12031 12030 12029 12028 12027 12026 12025 12024 12023 12022 12021 12020 12019 12018 12017 12016 12015 12014 12013 12012 12011 12010 12009 12008 12007 12006 12005 12004 12003 12002 12001 12000 11999 11998 11997 11996 11995 11994 11993 11992 11991 11990 11989 11988 11987 11986 11985 11984 11983 11982 11981 11980 11979 11978 11977 11976 11975 11974 11973 11972 11971 11970 11969 11968 11967 11966 11965 11964 11963 11962 11961 11960 11959 11958 11957 11956 11955 11954 11953 11952 11951 11950 11949 11948 11947 11946 11945 11944 11943 11942 11941 11940 11939 11938 11937 11936 11935 11934 11933 11932 11931 11930 11929 11928 11927 11926 11925 11924 11923 11922 11921 11920 11919 11918 11917 11916 11915 11914 11913 11912 11911 11910 11909 11908 11907 11906 11905 11904 11903 11902 11901 11900 11899 11898 11897 11896 11895 11894 11893 11892 11891 11890 11889 11888 11887 11886 11885 11884 11883 11882 11881 11880 11879 11878 11877 11876 11875 11874 11873 11872 11871 11870 11869 11868 11867 11866 11865 11864 11863 11862 11861 11860 11859 11858 11857 11856 11855 11854 11853 11852 11851 11850 11849 11848 11847 11846 11845 11844 11843 11842 11841 11840 11839 11838 11837 11836 11835 11834 11833 11832 11831 11830 11829 11828 11827 11826 11825 11824 11823 11822 11821 11820 11819 11818 11817 11816 11815 11814 11813 11812 11811 11810 11809 11808 11807 11806 11805 11804 11803 11802 11801 11800 11799 11798 11797 11796 11795 11794 11793 11792 11791 11790 11789 11788 11787 11786 11785 11784 11783 11782 11781 11780 11779 11778 11777 11776 11775 11774 11773 11772 11771 11770 11769 11768 11767 11766 11765 11764 11763 11762 11761 11760 11759 11758 11757 11756 11755 11754 11753 11752 11751 11750 11749 11748 11747 11746 11745 11744 11743 11742 11741 11740 11739 11738 11737 11736 11735 11734 11733 11732 11731 11730 11729 11728 11727 11726 11725 11724 11723 11722 11721 11720 11719 11718 11717 11716 11715 11714 11713 11712 11711 11710 11709 11708 11707 11706 11705 11704 11703 11702 11701 11700 11699 11698 11697 11696 11695 11694 11693 11692 11691 11690 11689 11688 11687 11686 11685 11684 11683 11682 11681 11680 11679 11678 11677 11676 11675 11674 11673 11672 11671 11670 11669 11668 11667 11666 11665 11664 11663 11662 11661 11660 11659 11658 11657 11656 11655 11654 11653 11652 11651 11650 11649 11648 11647 11646 11645 11644 11643 11642 11641 11640 11639 11638 11637 11636 11635 11634 11633 11632 11631 11630 11629 11628 11627 11626 11625 11624 11623 11622 11621 11620 11619 11618 11617 11616 11615 11614 11613 11612 11611 11610 11609 11608 11607 11606 11605 11604 11603 11602 11601 11600 11599 11598 11597 11596 11595 11594 11593 11592 11591 11590 11589 11588 11587 11586 11585 11584 11583 11582 11581 11580 11579 11578 11577 11576 11575 11574 11573 11572 11571 11570 11569 11568 11567 11566 11565 11564 11563 11562 11561 11560 11559 11558 11557 11556 11555 11554 11553 11552 11551 11550 11549 11548 11547 11546 11545 11544 11543 11542 11541 11540 11539 11538 11537 11536 11535 11534 11533 11532 11531 11530 11529 11528 11527 11526 11525 11524 11523 11522 11521 11520 11519 11518 11517 11516 11515 11514 11513 11512 11511 11510 11509 11508 11507 11506 11505 11504 11503 11502 11501 11500 11499 11498 11497 11496 11495 11494 11493 11492 11491 11490 11489 11488 11487 11486 11485 11484 11483 11482 11481 11480 11479 11478 11477 11476 11475 11474 11473 11472 11471 11470 11469 11468 11467 11466 11465 11464 11463 11462 11461 11460 11459 11458 11457 11456 11455 11454 11453 11452 11451 11450 11449 11448 11447 11446 11445 11444 11443 11442 11441 11440 11439 11438 11437 11436 11435 11434 11433 11432 11431 11430 11429 11428 11427 11426 11425 11424 11423 11422 11421 11420 11419 11418 11417 11416 11415 11414 11413 11412 11411 11410 11409 11408 11407 11406 11405 11404 11403 11402 11401 11400 11399 11398 11397 11396 11395 11394 11393 11392 11391 11390 11389 11388 11387 11386 11385 11384 11383 11382 11381 11380 11379 11378 11377 11376 11375 11374 11373 11372 11371 11370 11369 11368 11367 11366 11365 11364 11363 11362 11361 11360 11359 11358 11357 11356 11355 11354 11353 11352 11351 11350 11349 11348 11347 11346 11345 11344 11343 11342 11341 11340 11339 11338 11337 11336 11335 11334 11333 11332 11331 11330 11329 11328 11327 11326 11325 11324 11323 11322 11321 11320 11319 11318 11317 11316 11315 11314 11313 11312 11311 11310 11309 11308 11307 11306 11305 11304 11303 11302 11301 11300 11299 11298 11297 11296 11295 11294 11293 11292 11291 11290 11289 11288 11287 11286 11285 11284 11283 11282 11281 11280 11279 11278 11277 11276 11275 11274 11273 11272 11271 11270 11269 11268 11267 11266 11265 11264 11263 11262 11261 11260 11259 11258 11257 11256 11255 11254 11253 11252 11251 11250 11249 11248 11247 11246 11245 11244 11243 11242 11241 11240 11239 11238 11237 11236 11235 11234 11233 11232 11231 11230 11229 11228 11227 11226 11225 11224 11223 11222 11221 11220 11219 11218 11217 11216 11215 11214 11213 11212 11211 11210 11209 11208 11207 11206 11205 11204 11203 11202 11201 11200 11199 11198 11197 11196 11195 11194 11193 11192 11191 11190 11189 11188 11187 11186 11185 11184 11183 11182 11181 11180 11179 11178 11177 11176 11175 11174 11173 11172 11171 11170 11169 11168 11167 11166 11165 11164 11163 11162 11161 11160 11159 11158 11157 11156 11155 11154 11153 11152 11151 11150 11149 11148 11147 11146 11145 11144 11143 11142 11141 11140 11139 11138 11137 11136 11135 11134 11133 11132 11131 11130 11129 11128 11127 11126 11125 11124 11123 11122 11121 11120 11119 11118 11117 11116 11115 11114 11113 11112 11111 11110 11109 11108 11107 11106 11105 11104 11103 11102 11101 11100 11099 11098 11097 11096 11095 11094 11093 11092 11091 11090 11089 11088 11087 11086 11085 11084 11083 11082 11081 11080 11079 11078 11077 11076 11075 11074 11073 11072 11071 11070 11069 11068 11067 11066 11065 11064 11063 11062 11061 11060 11059 11058 11057 11056 11055 11054 11053 11052 11051 11050 11049 11048 11047 11046 11045 11044 11043 11042 11041 11040 11039 11038 11037 11036 11035 11034 11033 11032 11031 11030 11029 11028 11027 11026 11025 11024 11023 11022 11021 11020 11019 11018 11017 11016 11015 11014 11013 11012 11011 11010 11009 11008 11007 11006 11005 11004 11003 11002 11001 11000 10999 10998 10997 10996 10995 10994 10993 10992 10991 10990 10989 10988 10987 10986 10985 10984 10983 10982 10981 10980 10979 10978 10977 10976 10975 10974 10973 10972 10971 10970 10969 10968 10967 10966 10965 10964 10963 10962 10961 10960 10959 10958 10957 10956 10955 10954 10953 10952 10951 10950 10949 10948 10947 10946 10945 10944 10943 10942 10941 10940 10939 10938 10937 10936 10935 10934 10933 10932 10931 10930 10929 10928 10927 10926 10925 10924 10923 10922 10921 10920 10919 10918 10917 10916 10915 10914 10913 10912 10911 10910 10909 10908 10907 10906 10905 10904 10903 10902 10901 10900 10899 10898 10897 10896 10895 10894 10893 10892 10891 10890 10889 10888 10887 10886 10885 10884 10883 10882 10881 10880 10879 10878 10877 10876 10875 10874 10873 10872 10871 10870 10869 10868 10867 10866 10865 10864 10863 10862 10861 10860 10859 10858 10857 10856 10855 10854 10853 10852 10851 10850 10849 10848 10847 10846 10845 10844 10843 10842 10841 10840 10839 10838 10837 10836 10835 10834 10833 10832 10831 10830 10829 10828 10827 10826 10825 10824 10823 10822 10821 10820 10819 10818 10817 10816 10815 10814 10813 10812 10811 10810 10809 10808 10807 10806 10805 10804 10803 10802 10801 10800 10799 10798 10797 10796 10795 10794 10793 10792 10791 10790 10789 10788 10787 10786 10785 10784 10783 10782 10781 10780 10779 10778 10777 10776 10775 10774 10773 10772 10771 10770 10769 10768 10767 10766 10765 10764 10763 10762 10761 10760 10759 10758 10757 10756 10755 10754 10753 10752 10751 10750 10749 10748 10747 10746 10745 10744 10743 10742 10741 10740 10739 10738 10737 10736 10735 10734 10733 10732 10731 10730 10729 10728 10727 10726 10725 10724 10723 10722 10721 10720 10719 10718 10717 10716 10715 10714 10713 10712 10711 10710 10709 10708 10707 10706 10705 10704 10703 10702 10701 10700 10699 10698 10697 10696 10695 10694 10693 10692 10691 10690 10689 10688 10687 10686 10685 10684 10683 10682 10681 10680 10679 10678 10677 10676 10675 10674 10673 10672 10671 10670 10669 10668 10667 10666 10665 10664 10663 10662 10661 10660 10659 10658 10657 10656 10655 10654 10653 10652 10651 10650 10649 10648 10647 10646 10645 10644 10643 10642 10641 10640 10639 10638 10637 10636 10635 10634 10633 10632 10631 10630 10629 10628 10627 10626 10625 10624 10623 10622 10621 10620 10619 10618 10617 10616 10615 10614 10613 10612 10611 10610 10609 10608 10607 10606 10605 10604 10603 10602 10601 10600 10599 10598 10597 10596 10595 10594 10593 10592 10591 10590 10589 10588 10587 10586 10585 10584 10583 10582 10581 10580 10579 10578 10577 10576 10575 10574 10573 10572 10571 10570 10569 10568 10567 10566 10565 10564 10563 10562 10561 10560 10559 10558 10557 10556 10555 10554 10553 10552 10551 10550 10549 10548 10547 10546 10545 10544 10543 10542 10541 10540 10539 10538 10537 10536 10535 10534 10533 10532 10531 10530 10529 10528 10527 10526 10525 10524 10523 10522 10521 10520 10519 10518 10517 10516 10515 10514 10513 10512 10511 10510 10509 10508 10507 10506 10505 10504 10503 10502 10501 10500 10499 10498 10497 10496 10495 10494 10493 10492 10491 10490 10489 10488 10487 10486 10485 10484 10483 10482 10481 10480 10479 10478 10477 10476 10475 10474 10473 10472 10471 10470 10469 10468 10467 10466 10465 10464 10463 10462 10461 10460 10459 10458 10457 10456 10455 10454 10453 10452 10451 10450 10449 10448 10447 10446 10445 10444 10443 10442 10441 10440 10439 10438 10437 10436 10435 10434 10433 10432 10431 10430 10429 10428 10427 10426 10425 10424 10423 10422 10421 10420 10419 10418 10417 10416 10415 10414 10413 10412 10411 10410 10409 10408 10407 10406 10405 10404 10403 10402 10401 10400 10399 10398 10397 10396 10395 10394 10393 10392 10391 10390 10389 10388 10387 10386 10385 10384 10383 10382 10381 10380 10379 10378 10377 10376 10375 10374 10373 10372 10371 10370 10369 10368 10367 10366 10365 10364 10363 10362 10361 10360 10359 10358 10357 10356 10355 10354 10353 10352 10351 10350 10349 10348 10347 10346 10345 10344 10343 10342 10341 10340 10339 10338 10337 10336 10335 10334 10333 10332 10331 10330 10329 10328 10327 10326 10325 10324 10323 10322 10321 10320 10319 10318 10317 10316 10315 10314 10313 10312 10311 10310 10309 10308 10307 10306 10305 10304 10303 10302 10301 10300 10299 10298 10297 10296 10295 10294 10293 10292 10291 10290 10289 10288 10287 10286 10285 10284 10283 10282 10281 10280 10279 10278 10277 10276 10275 10274 10273 10272 10271 10270 10269 10268 10267 10266 10265 10264 10263 10262 10261 10260 10259 10258 10257 10256 10255 10254 10253 10252 10251 10250 10249 10248 10247 10246 10245 10244 10243 10242 10241 10240 10239 10238 10237 10236 10235 10234 10233 10232 10231 10230 10229 10228 10227 10226 10225 10224 10223 10222 10221 10220 10219 10218 10217 10216 10215 10214 10213 10212 10211 10210 10209 10208 10207 10206 10205 10204 10203 10202 10201 10200 10199 10198 10197 10196 10195 10194 10193 10192 10191 10190 10189 10188 10187 10186 10185 10184 10183 10182 10181 10180 10179 10178 10177 10176 10175 10174 10173 10172 10171 10170 10169 10168 10167 10166 10165 10164 10163 10162 10161 10160 10159 10158 10157 10156 10155 10154 10153 10152 10151 10150 10149 10148 10147 10146 10145 10144 10143 10142 10141 10140 10139 10138 10137 10136 10135 10134 10133 10132 10131 10130 10129 10128 10127 10126 10125 10124 10123 10122 10121 10120 10119 10118 10117 10116 10115 10114 10113 10112 10111 10110 10109 10108 10107 10106 10105 10104 10103 10102 10101 10100 10099 10098 10097 10096 10095 10094 10093 10092 10091 10090 10089 10088 10087 10086 10085 10084 10083 10082 10081 10080 10079 10078 10077 10076 10075 10074 10073 10072 10071 10070 10069 10068 10067 10066 10065 10064 10063 10062 10061 10060 10059 10058 10057 10056 10055 10054 10053 10052 10051 10050 10049 10048 10047 10046 10045 10044 10043 10042 10041 10040 10039 10038 10037 10036 10035 10034 10033 10032 10031 10030 10029 10028 10027 10026 10025 10024 10023 10022 10021 10020 10019 10018 10017 10016 10015 10014 10013 10012 10011 10010 10009 10008 10007 10006 10005 10004 10003 10002 10001 10000 9999 9998 9997 9996 9995 9994 9993 9992 9991 9990 9989 9988 9987 9986 9985 9984 9983 9982 9981 9980 9979 9978 9977 9976 9975 9974 9973 9972 9971 9970 9969 9968 9967 9966 9965 9964 9963 9962 9961 9960 9959 9958 9957 9956 9955 9954 9953 9952 9951 9950 9949 9948 9947 9946 9945 9944 9943 9942 9941 9940 9939 9938 9937 9936 9935 9934 9933 9932 9931 9930 9929 9928 9927 9926 9925 9924 9923 9922 9921 9920 9919 9918 9917 9916 9915 9914 9913 9912 9911 9910 9909 9908 9907 9906 9905 9904 9903 9902 9901 9900 9899 9898 9897 9896 9895 9894 9893 9892 9891 9890 9889 9888 9887 9886 9885 9884 9883 9882 9881 9880 9879 9878 9877 9876 9875 9874 9873 9872 9871 9870 9869 9868 9867 9866 9865 9864 9863 9862 9861 9860 9859 9858 9857 9856 9855 9854 9853 9852 9851 9850 9849 9848 9847 9846 9845 9844 9843 9842 9841 9840 9839 9838 9837 9836 9835 9834 9833 9832 9831 9830 9829 9828 9827 9826 9825 9824 9823 9822 9821 9820 9819 9818 9817 9816 9815 9814 9813 9812 9811 9810 9809 9808 9807 9806 9805 9804 9803 9802 9801 9800 9799 9798 9797 9796 9795 9794 9793 9792 9791 9790 9789 9788 9787 9786 9785 9784 9783 9782 9781 9780 9779 9778 9777 9776 9775 9774 9773 9772 9771 9770 9769 9768 9767 9766 9765 9764 9763 9762 9761 9760 9759 9758 9757 9756 9755 9754 9753 9752 9751 9750 9749 9748 9747 9746 9745 9744 9743 9742 9741 9740 9739 9738 9737 9736 9735 9734 9733 9732 9731 9730 9729 9728 9727 9726 9725 9724 9723 9722 9721 9720 9719 9718 9717 9716 9715 9714 9713 9712 9711 9710 9709 9708 9707 9706 9705 9704 9703 9702 9701 9700 9699 9698 9697 9696 9695 9694 9693 9692 9691 9690 9689 9688 9687 9686 9685 9684 9683 9682 9681 9680 9679 9678 9677 9676 9675 9674 9673 9672 9671 9670 9669 9668 9667 9666 9665 9664 9663 9662 9661 9660 9659 9658 9657 9656 9655 9654 9653 9652 9651 9650 9649 9648 9647 9646 9645 9644 9643 9642 9641 9640 9639 9638 9637 9636 9635 9634 9633 9632 9631 9630 9629 9628 9627 9626 9625 9624 9623 9622 9621 9620 9619 9618 9617 9616 9615 9614 9613 9612 9611 9610 9609 9608 9607 9606 9605 9604 9603 9602 9601 9600 9599 9598 9597 9596 9595 9594 9593 9592 9591 9590 9589 9588 9587 9586 9585 9584 9583 9582 9581 9580 9579 9578 9577 9576 9575 9574 9573 9572 9571 9570 9569 9568 9567 9566 9565 9564 9563 9562 9561 9560 9559 9558 9557 9556 9555 9554 9553 9552 9551 9550 9549 9548 9547 9546 9545 9544 9543 9542 9541 9540 9539 9538 9537 9536 9535 9534 9533 9532 9531 9530 9529 9528 9527 9526 9525 9524 9523 9522 9521 9520 9519 9518 9517 9516 9515 9514 9513 9512 9511 9510 9509 9508 9507 9506 9505 9504 9503 9502 9501 9500 9499 9498 9497 9496 9495 9494 9493 9492 9491 9490 9489 9488 9487 9486 9485 9484 9483 9482 9481 9480 9479 9478 9477 9476 9475 9474 9473 9472 9471 9470 9469 9468 9467 9466 9465 9464 9463 9462 9461 9460 9459 9458 9457 9456 9455 9454 9453 9452 9451 9450 9449 9448 9447 9446 9445 9444 9443 9442 9441 9440 9439 9438 9437 9436 9435 9434 9433 9432 9431 9430 9429 9428 9427 9426 9425 9424 9423 9422 9421 9420 9419 9418 9417 9416 9415 9414 9413 9412 9411 9410 9409 9408 9407 9406 9405 9404 9403 9402 9401 9400 9399 9398 9397 9396 9395 9394 9393 9392 9391 9390 9389 9388 9387 9386 9385 9384 9383 9382 9381 9380 9379 9378 9377 9376 9375 9374 9373 9372 9371 9370 9369 9368 9367 9366 9365 9364 9363 9362 9361 9360 9359 9358 9357 9356 9355 9354 9353 9352 9351 9350 9349 9348 9347 9346 9345 9344 9343 9342 9341 9340 9339 9338 9337 9336 9335 9334 9333 9332 9331 9330 9329 9328 9327 9326 9325 9324 9323 9322 9321 9320 9319 9318 9317 9316 9315 9314 9313 9312 9311 9310 9309 9308 9307 9306 9305 9304 9303 9302 9301 9300 9299 9298 9297 9296 9295 9294 9293 9292 9291 9290 9289 9288 9287 9286 9285 9284 9283 9282 9281 9280 9279 9278 9277 9276 9275 9274 9273 9272 9271 9270 9269 9268 9267 9266 9265 9264 9263 9262 9261 9260 9259 9258 9257 9256 9255 9254 9253 9252 9251 9250 9249 9248 9247 9246 9245 9244 9243 9242 9241 9240 9239 9238 9237 9236 9235 9234 9233 9232 9231 9230 9229 9228 9227 9226 9225 9224 9223 9222 9221 9220 9219 9218 9217 9216 9215 9214 9213 9212 9211 9210 9209 9208 9207 9206 9205 9204 9203 9202 9201 9200 9199 9198 9197 9196 9195 9194 9193 9192 9191 9190 9189 9188 9187 9186 9185 9184 9183 9182 9181 9180 9179 9178 9177 9176 9175 9174 9173 9172 9171 9170 9169 9168 9167 9166 9165 9164 9163 9162 9161 9160 9159 9158 9157 9156 9155 9154 9153 9152 9151 9150 9149 9148 9147 9146 9145 9144 9143 9142 9141 9140 9139 9138 9137 9136 9135 9134 9133 9132 9131 9130 9129 9128 9127 9126 9125 9124 9123 9122 9121 9120 9119 9118 9117 9116 9115 9114 9113 9112 9111 9110 9109 9108 9107 9106 9105 9104 9103 9102 9101 9100 9099 9098 9097 9096 9095 9094 9093 9092 9091 9090 9089 9088 9087 9086 9085 9084 9083 9082 9081 9080 9079 9078 9077 9076 9075 9074 9073 9072 9071 9070 9069 9068 9067 9066 9065 9064 9063 9062 9061 9060 9059 9058 9057 9056 9055 9054 9053 9052 9051 9050 9049 9048 9047 9046 9045 9044 9043 9042 9041 9040 9039 9038 9037 9036 9035 9034 9033 9032 9031 9030 9029 9028 9027 9026 9025 9024 9023 9022 9021 9020 9019 9018 9017 9016 9015 9014 9013 9012 9011 9010 9009 9008 9007 9006 9005 9004 9003 9002 9001
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==0.78.4', 'console_scripts', 'sshuttle')()
  File "/usr/lib/python3.6/site-packages/sshuttle/cmdline.py", line 79, in main
    opt.user)
  File "/usr/lib/python3.6/site-packages/sshuttle/client.py", line 688, in main
    raise last_e
  File "/usr/lib/python3.6/site-packages/sshuttle/client.py", line 672, in main
    tcp_listener.bind(lv6, lv4)
  File "/usr/lib/python3.6/site-packages/sshuttle/client.py", line 168, in bind
    self.v4.bind(address_v4)
OSError: [Errno 98] Address already in use
```

**Comment by brianmay** [comment]
This seems to indicate that every time we try to bind we get an `EADDRINUSE`.

Possibly we should not print the port number for every attempt for every port, however it it handy to have this information in this particular case.

I have no idea why you would be getting `EADDRINUSE`. This seems to suggest something is wrong with your kernel. What OS are you running?

**Comment by brianjmurrell** [comment]
I really doubt there is something wrong with my kernel.  It's Fedora Linux and this has been ongoing for a long time across many many kernels from Fedora.

I would imagine any bug that produced this kind of error while properly using sockets would get ferreted out pretty quickly.

I agree though that it's not at all likely that 12300-9000 ports are all in use for the short period of time after sshuttle stops and wants to restart and then become available some few 10s of seconds later.

**Comment by brianmay** [comment]
Can you please show the full command line you use to start sshuttle? Thanks

**Comment by brianjmurrell** [comment]
> Can you please show the full command line you use to start sshuttle?

```
sshuttle --dns -l 12304 --ns-hosts 127.10.0.4 -Nvvvr 
```

Looking at the code, the `port` that ranges through `ports` isn't always used.  For example, in this code:

```
        if listenip_v4 and listenip_v4[1]:
            lv4 = listenip_v4
            redirectport_v4 = lv4[1]
        elif listenip_v4:
            lv4 = (listenip_v4[0], port)
            redirectport_v4 = port
        else:
            lv4 = None
            redirectport_v4 = 0
```
`port` is actually only used in the second branch of code.  So what's the point of ranging through `ports` when the first (`if`) or third (`else`) branch of code is being used?  Just to retry the bind repeatedly in hopes that a transient problem goes away?

**Comment by brianmay** [comment]
Here it looks like you have specified a port to connect to on the command line. Do you really need this `-l 12304` argument? Yes it does look like we handle this case badly.

**Comment by brianjmurrell** [comment]
I don't recall the specifics but believe I am using `-l 12304` to fix the DNS proxy to a specific port so that I can configure my caching BIND server to forward requests for the remote domain to _sshuttle_:
```
zone "corporate.example.com" IN {
	type forward;
	forwarders { 127.10.0.4; };
};
```

**Comment by brianjmurrell** [comment]
So, after having to interrupt `sshuttle`, trying to restart it will hit this if the socket is still in TIME_WAIT:

```
tcp        0      0 127.0.0.1:12304         10.252.132.51:36324     TIME_WAIT   -                   
```

Should there be some use of `SO_REUSEADDR` to prevent this and allow an `sshuttle` to be restarted immediately after being interrupted?

**Comment by Flameopathic** [comment]
I am having the same problem, except I am not specifying a port.
```bash
[flame@surfnix:/etc/nixos]$ sudo sshuttle 0.0.0.0/0 -r 107.202.30.255 --method tproxy -e 'ssh -i /home/flame/.ssh/id_ed25519' --exclude 107.202.30.255
c : Connected to server.
Traceback (most recent call last):
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/bin/..sshuttle-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/cmdline.py", line 98, in main
    return_code = client.main(ipport_v6, ipport_v4,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/client.py", line 1103, in main
    return _main(tcp_listener, udp_listener, fw, ssh_cmd, remotename,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/client.py", line 748, in _main
    ssnet.runonce(handlers, mux)
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/ssnet.py", line 608, in runonce
    h.callback(s)
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/ssnet.py", line 496, in callback
    self.handle()
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/ssnet.py", line 484, in handle
    self.got_packet(channel, cmd, data)
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/ssnet.py", line 431, in got_packet
    callback(cmd, data)
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/client.py", line 500, in <lambda>
    mux.channels[chan] = lambda cmd, data: udp_done(
                                           ^^^^^^^^^
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/client.py", line 486, in udp_done
    method.send_udp(sock, srcip, dstip, data)
  File "/nix/store/pq4kxpmxg9lc2clih8vn373y6f0qp316-sshuttle-1.1.2/lib/python3.11/site-packages/sshuttle/methods/tproxy.py", line 94, in send_udp
    sender.bind(srcip)
OSError: [Errno 98] Address already in use
```
