### ISSUE TITLE
No such file or directory: '/dev/null' on Windows with Cmder

### ISSUE THREAD

**Issue by AbbalYouness** [sshuttle/sshuttle#279]
Hello,
I use Cmder as a terminal for Windows.
I got an error when I use it to forward some ip from a VM to my host.
It's just about there is no directory `/dev/null` on Windows
There is the trace of the error : 
```Traceback (most recent call last):
  File "c:\users\me\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\Scripts\sshuttle.exe\__main__.py", line 5, in <module>
  File "c:\users\me\appdata\local\programs\python\python36-32\lib\site-packages\sshuttle\cmdline.py", line 4, in <module>
    import sshuttle.client as client
  File "c:\users\me\appdata\local\programs\python\python36-32\lib\site-packages\sshuttle\client.py", line 36, in <module>
    _extra_fd = os.open('/dev/null', os.O_RDONLY)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/null'
```
A way to solve this problem, is maybe to use `os.devnull from` the package os instead of directly write `'/dev/null'`
Thank you of any response ^^

**Comment by brianmay** [comment]
Pull requests to fix this welcome :-)

**Comment by brianmay** [comment]
Fixed by #918.
