### ISSUE TITLE
socket.gaierror: [Errno -9] Address family for hostname not supported reports when I open facebook with dns forward on.

### ISSUE THREAD

**Issue by d0u9** [sshuttle/sshuttle#28]
I started sshuttl with `sshuttle --dns -vvr username@server 0/0`.  then when I access `www.facebook.com` in Chrome, sshuttle crashed, and `socket.gaierror: [Errno -9] Address family for hostname not supported` is dumped.

below is the full traceback dumped by sshuttle:

```
 s:   Ready: 3 r=[4] w=[] x=[]
 s: <  channel=4 cmd=DNS_REQ len=34
 s: Incoming DNS request channel=4.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 27, in <module>
  File "server.py", line 318, in main
  File "ssnet.py", line 573, in runonce
  File "ssnet.py", line 474, in callback
  File "ssnet.py", line 462, in handle
  File "ssnet.py", line 397, in got_packet
  File "server.py", line 277, in dns_req
  File "server.py", line 139, in __init__
  File "server.py", line 147, in try_send
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno -9] Address family for hostname not supported
 s: SW'unknown':Mux#3: deleting (5 remain)
 s: SW#8:159.106.121.75:443: deleting (4 remain)
c :   Ready: 5 r=[9] w=[] x=[]
c : SW#11:10.210.97.16:61804: deleting (5 remain)
c : SW'unknown':Mux#3: deleting (4 remain)
firewall manager: undoing changes.
>> pfctl -a sshuttle -F all
>> pfctl -X 3691003263071173557
c : fatal: server died with error code 1
c : SW#10:10.210.97.16:61803: deleting (3 remain)
c : SW#8:10.210.97.16:61807: deleting (2 remain)
```

I tried on Ubuntu and OSX 10.11 El captain and encountered same problem.

**Comment by brianmay** [comment]
Hello,

Can you please copy and paste the `/etc/resolv.conf` from your server here? There is a known bug contacting servers with IPv6 addresses, I suspect that might be what you are seeing here.

Thanks

**Comment by d0u9** [comment]
The system of my server is Ubuntu 14.04 LTS. 

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 2001:4860:4860::8844
nameserver 2001:4860:4860::8888
nameserver 8.8.8.8
```

**Comment by brianmay** [comment]
Yes, that does look like the same problem. I just pushed a change to fix this in the cleanup branch, and will move to the master branch very soon now.
