### ISSUE TITLE
sshuttle triggers exception on nmap scan

### ISSUE THREAD

**Issue by ajinabraham** [sshuttle/sshuttle#287]
```
sshuttle --dns -r foo@bastion:2222 10.1.0.0/16
client: Connected
```
Run Nmap on a different tab
```
 nmap -F 10.1.2.3
```
It cause an exception and kills sshuttle
```
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==0.78.4', 'console_scripts', 'sshuttle')()
  File "/usr/local/Cellar/sshuttle/0.78.4_1/libexec/lib/python3.7/site-packages/sshuttle/cmdline.py", line 79, in main
    opt.user)
  File "/usr/local/Cellar/sshuttle/0.78.4_1/libexec/lib/python3.7/site-packages/sshuttle/client.py", line 778, in main
    seed_hosts, auto_hosts, auto_nets, daemon, to_nameserver)
  File "/usr/local/Cellar/sshuttle/0.78.4_1/libexec/lib/python3.7/site-packages/sshuttle/client.py", line 538, in _main
    ssnet.runonce(handlers, mux)
  File "/usr/local/Cellar/sshuttle/0.78.4_1/libexec/lib/python3.7/site-packages/sshuttle/ssnet.py", line 596, in runonce
    h.callback(s)
  File "/usr/local/Cellar/sshuttle/0.78.4_1/libexec/lib/python3.7/site-packages/sshuttle/client.py", line 139, in <lambda>
    lambda sock: callback(sock, method, mux, handlers)
  File "/usr/local/Cellar/sshuttle/0.78.4_1/libexec/lib/python3.7/site-packages/sshuttle/client.py", line 355, in onaccept_tcp
    dstip = method.get_tcp_dstip(sock)
  File "/usr/local/Cellar/sshuttle/0.78.4_1/libexec/lib/python3.7/site-packages/sshuttle/methods/pf.py", line 423, in get_tcp_dstip
    peer = sock.getpeername()
OSError: [Errno 22] Invalid argument
```

**Comment by brianmay** [comment]
What OS is this on?

**Comment by ajinabraham** [comment]
osx high sierra

**Comment by bertjwregeer** [comment]
This also happens on MacOS Mojave.

**Comment by lucasapa** [comment]
I have the same issue

**Comment by haruo31** [comment]
My friend had the same issue, but it did not reproduce after reboot the Mac.

**Comment by sholland** [comment]
I get the same error, even after a reboot

**Comment by parthspatel** [comment]
Getting this error even after reboot on macOS Catalina
