### ISSUE TITLE
Failed to launch without '-v'

### ISSUE THREAD

**Issue by felixonmars** [sshuttle/sshuttle#31]
Looks like helpers.verbose was initialized to None instead of 0 somewhere, but I failed to find it out.

```
$ sshuttle -r myhost 0/0
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.73', 'console_scripts', 'sshuttle')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2704, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2377, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2383, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/sshuttle/__main__.py", line 212, in <module>
    opt.syslog, opt.daemon, opt.pidfile)
  File "/usr/lib/python3.5/site-packages/sshuttle/client.py", line 502, in main
    debug1('Starting sshuttle proxy.\n')
  File "/usr/lib/python3.5/site-packages/sshuttle/helpers.py", line 21, in debug1
    if verbose >= 1:
TypeError: unorderable types: NoneType() >= int()
```

**Comment by brianmay** [comment]
Think that is the weird command line parser that is used from sshuttle.options. I don't particularly like the way this is done, however it hasn't annoyed me enough yet to change it. I think because -v isn't used, the command line parser gives None instead of 0. Yuck.

Probably I always test with -vvv so I didn't notice this...

(more tests to catch errors like this would also be good)

**Comment by brianmay** [comment]
Oh, I see, this looks like a bug that only occurs with Python3.5 and only if you don't specify `-v` on the command line. `None >= 1` is a valid operation in Python2.7. Will fix this.

**Comment by matiwinnetou** [comment]
Even though I use -v I seem to still get the issue:

[mszczap@d-txl-00445584 ~]$ sshuttle -v -H --dns -r pi@matiwinnetou.no-ip.org 192.168.1.0/24
Starting sshuttle proxy.
firewall manager ready method name nat.
UDP enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12300).
c : connecting to server...
 s: latency control setting = True
 s: available routes:
 s:   2/172.17.0.0/16
 s:   2/192.168.1.0/24
 s:   2/192.168.1.1/32
c : connected.
Connected.
c : seed_hosts: []
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.73', 'console_scripts', 'sshuttle')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2721, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2377, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2383, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/sshuttle/__main__.py", line 212, in <module>
    opt.syslog, opt.daemon, opt.pidfile)
  File "/usr/lib/python3.5/site-packages/sshuttle/client.py", line 644, in main
    daemon)
  File "/usr/lib/python3.5/site-packages/sshuttle/client.py", line 477, in _main
    mux.send(0, ssnet.CMD_HOST_REQ, '\n'.join(seed_hosts))
  File "/usr/lib/python3.5/site-packages/sshuttle/ssnet.py", line 369, in send
    assert isinstance(data, bytes)
AssertionError

**Comment by felixonmars** [comment]
It doesn't look like the same issue to me.

**Comment by matiwinnetou** [comment]
ok, interesting.

**Comment by matiwinnetou** [comment]
I am on arch linux and this is my python setup:
[mszczap@d-txl-00445584 ~]$ python
Python 3.5.0 (default, Sep 20 2015, 11:28:25) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by matiwinnetou** [comment]
I switched to python 2.7 to check if problem is there as well:

[mszczap@d-txl-00445584 ~]$ sshuttle -v -H --dns -r pi@matiwinnetou.no-ip.org 192.168.1.0/24
Starting sshuttle proxy.
firewall manager ready method name nat.
UDP enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12300).
c : connecting to server...
 s: latency control setting = True
 s: available routes:
 s:   2/172.17.0.0/16
 s:   2/192.168.1.0/24
 s:   2/192.168.1.1/32
c : connected.
Connected.
c : seed_hosts: []
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.73', 'console_scripts', 'sshuttle')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2721, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2377, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2383, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/sshuttle/__main__.py", line 212, in <module>
    opt.syslog, opt.daemon, opt.pidfile)
  File "/usr/lib/python3.5/site-packages/sshuttle/client.py", line 644, in main
    daemon)
  File "/usr/lib/python3.5/site-packages/sshuttle/client.py", line 477, in _main
    mux.send(0, ssnet.CMD_HOST_REQ, '\n'.join(seed_hosts))
  File "/usr/lib/python3.5/site-packages/sshuttle/ssnet.py", line 369, in send
    assert isinstance(data, bytes)
AssertionError
[mszczap@d-txl-00445584 ~]$ python --version
Python 2.7.10
[mszczap@d-txl-00445584 ~]$

**Comment by felixonmars** [comment]
You can try with my patch in #33.

**Comment by matiwinnetou** [comment]
thx, I will give it a try.

**Comment by brianmay** [comment]
Not convinced that this is #33. If it was the same thing, the problem should go away for Python 2.7 as bytes==str.

Then again, are you absolutely sure you really did get Python 2.7 when you intended? Might be useful to get sshuttle to display what Python version it is being called with, I suspect you might have got Python 3.5 by mistake.

This really does look like the Python 3.5 specific issue.

**Comment by brianmay** [comment]
Just pushed a change to print the Python version while running the different parts of sshuttle. 43d6ad6a51453f45ce4d69462ccd4a25872bf0c1

Noticed that the server is always being run with Python 2.7. There appear to be problems with running with Python 3, however my server only has Python 3.4 not Python 3.5.

**Comment by brianmay** [comment]
Transferred talk about the server issues to #34.

**Comment by brianmay** [comment]
Will close this again. Think I resolved @matiwinnetou issue too. If not, please open a new issue.
