### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '-l' when running on Vagrant

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [sshuttle/sshuttle#320]
Hello.

I have launched vagrant in my Windows PC and installed sshuttle. As it was written in this [instructions](https://github.com/sshuttle/sshuttle/blob/master/docs/windows.rst) I have run this command:

    sshuttle -l 0.0.0.0 -x 10.0.0.0/8 -x 192.168.0.0/16 0/0

It throws me this error:

    Traceback (most recent call last):
      File "/usr/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.76', 'console_scripts', 'sshuttle')()
      File "/usr/lib/python3/dist-packages/sshuttle/cmdline.py", line 226, in main
    opt.daemon, opt.pidfile)
      File "/usr/lib/python3/dist-packages/sshuttle/client.py", line 701, in main
    seed_hosts, auto_nets, daemon)
      File "/usr/lib/python3/dist-packages/sshuttle/client.py", line 408, in _main
    options=dict(latency_control=latency_control))
      File "/usr/lib/python3/dist-packages/sshuttle/ssh.py", line 125, in connect
    close_fds=True, stderr=stderr)
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '-l'

Why this is happening?

**Comment by brianmay** [comment]
Try running in verbose mode: `-vvv` - and copy the full output here.

**Comment by SuperMasterBlasterLaser** [comment]
@brianmay I just installed sshuttle from pip and it worked. This error happened when I installed it from apt
