### ISSUE TITLE
c : fatal: expected server init string b'SSHUTTLE0001'; got b''

### ISSUE THREAD

**Issue by yangliping** [sshuttle/sshuttle#328]
Hi,

I want to use sshuttle to connect to the intranet. There is a jump host between the client's network and intranet. TCP Forwarding is disabled in the jump host, and login the jump host will prompt for host selection. I can use the command `ssh test/remote.host.com/test@jump.host.com` login the remote host directly. How can I use sshuttle to create a VPN tunnel. Here's the debug output for the command I used.

```
$ sudo sshuttle -vvv -r test/remote.host.com/test@jump.host.com 0/0
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.5.0
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: False
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.5.0
c : connecting to server...
c : ssh_cmd: ssh
c : remotename: test/remote.host.com/test@jump.host.com
c : executing: ['ssh', 'test/remote.host.com/test@jump.host.com', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1106), "assembler.py", "exec"))\'"\'"\'\'']
Password authentication
Password:
c :  > channel=0 cmd=PING len=7 (fullness=0)
c : fatal: expected server init string b'SSHUTTLE0001'; got b''
```

**Comment by brianmay** [comment]
This message typically means that sshuttle failed to start on the remote server for some reason. Unfortunately it doesn't say why. Beginning to thing sshuttle really needs better feedback in this situation.

**Comment by raagamuffin** [comment]
For what its worth, I got the same error. I'm new to sshuttle and python, though I did find a workaround (if you can call it that).  If the python command on the remote server (Ubuntu) defaults to python 3.6+ rather than 2.x, the error goes away. (I still had to use the -x flag to prevent the 'broken pipe' error). 
I'm sure more knowledgeable individuals can help default the python command to version 3 via a user script etc. 
Versions used: 
Server: Ubuntu 18.04.1
client: Centos 7, Ubuntu 18.04.1
sshuttle version (client): CentOS - default from repo -V flag errors out, Ubuntu -  0.78.3
python version (client) : CentOS - python 2.7.5, Ubuntu - python 2.7.15rc1, python3 3.6.7
Hope this helps.

**Comment by yangliping** [comment]
I install python-3.7.3 in remote server (CentOS 6.9), and use `--python` argument to specify the python to use. I still get the same error. No 'broken pipe' error in my situation. There aren't enough feedback information from the server to identify the problem.

**Comment by konstruktoid** [comment]
Installing the same version of python on the sshuttle server as on the target node seems to fix this issue.

Server:
```
~$ lsb_release -a && dpkg -l | grep -E 'sshuttle|python.\s'
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

ii  python2                              2.7.17-1                          amd64        interactive high-level object-oriented language (Python2 version)
ii  python3                              3.7.5-1                           amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-minimal                      3.7.5-1                           amd64        minimal subset of the Python language (default python3 version)
ii  sshuttle                             0.78.5-1                          all          Transparent proxy server for VPN over SSH
```
Target node:
```
~$ lsb_release -a && dpkg -l | grep -E 'sshuttle|python.\s'
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch

ii  dh-python                       2.20170125                   all          Debian helper tools for packaging Python libraries and applications
ii  libpython3-stdlib:armhf         3.5.3-1                      armhf        interactive high-level object-oriented language (default python3 version)
ii  python                          2.7.13-2                     armhf        interactive high-level object-oriented language (default version)
ii  python3                         3.5.3-1                      armhf        interactive high-level object-oriented language (default python3 version)
ii  python3-minimal                 3.5.3-1                      armhf        minimal subset of the Python language (default python3 version)
```

```
~$ sshuttle --dns -r XXX@XXX 0/0
Raspbian GNU/Linux 9
XXX@XXX's password: 
rbash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
rbash: line 0: exec: restricted
client: fatal: expected server init string b'SSHUTTLE0001'; got b''
~$ sudo apt-get -y update && sudo apt-get -y install python2
~$ sshuttle --dns --python python2.7 -r XXX@XXX  0/0
Raspbian GNU/Linux 9
XXX@XXX 's password: 
rbash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
client: Connected.
^Cclient: 
client: Keyboard interrupt: exiting.
~$ sshuttle --dns --python python2.7 --disable-ipv6 --daemon -r XXX@XXX 0/0
XXX@XXX's password: 
~$ ps -fe | grep sshuttle
YYYY      7264     1  0 12:21 ?        00:00:00 /usr/bin/python3 /usr/bin/sshuttle --dns --python python2.7 --disable-ipv6 --daemon -r XXX@XXX 0/0
```

**Comment by brianmay** [comment]
@konstruktoid Do you have a restricted bash shell configured? The following line would suggest so:

```
rbash: line 0: exec: restricted
```

Also you can enable verbose mode with `-vvv`.

**Comment by konstruktoid** [comment]
@brianmay yeah, it's `rsh` but installing python2.7 on the target node and using `--python python2.7` fixes the issue. `sshuttle` works great after doing so.

**Comment by grrrrr** [comment]
@konstruktoid do you know what restrictions are in place for your `rsh`?  I am trying access like you and it would be nice to be able to give admin a list of what is needed.

**Comment by konstruktoid** [comment]
Updated version of https://github.com/sshuttle/sshuttle/issues/328#issuecomment-555983447.

On the target node/relay host/jump host/...:
```
$ sudo apt-get -y install sshuttle
$ which rbash
/bin/rbash
$ sudo useradd --create-home --system --shell /bin/rbash sshuttle
$ id sshuttle
uid=999(sshuttle) gid=998(sshuttle) groups=998(sshuttle)
$ passwd sshuttle ** but this is testing, you should be using proper keys **
$ lsb_release -a && dpkg -l | grep -E 'sshuttle|python.\s'
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
ii  libpython3-stdlib:armhf             3.6.7-1~18.04                       armhf        interactive high-level object-oriented language (default python3 version)
ii  python3                             3.6.7-1~18.04                       armhf        interactive high-level object-oriented language (default python3 version)
ii  python3-minimal                     3.6.7-1~18.04                       armhf        minimal subset of the Python language (default python3 version)
ii  sshuttle                            0.78.3-1ubuntu1                     all          Transparent proxy server for VPN over SSH
```

On the client (created using https://github.com/konstruktoid/hardening#test-automation-using-vagrant):
```
$ sudo apt-get -y install sshuttle
$ lsb_release -a && dpkg -l | grep -E 'sshuttle|python.\s'
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Focal Fossa (development branch)
Release:        20.04
Codename:       focal
ii  libpython3-stdlib:amd64        3.8.2-0ubuntu1                    amd64        interactive high-level object-oriented language (default python3 version)
ii  python3                        3.8.2-0ubuntu1                    amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-minimal                3.8.2-0ubuntu1                    amd64        minimal subset of the Python language (default python3 version)
ii  sshuttle                       0.78.5-1                          all          Transparent proxy server for VPN over SSH
$ sudo sshuttle --dns -r sshuttle@X.X.X.X 0/0
Ubuntu 18.04.4 LTS
sshuttle@192.168.0.95's password: 

rbash: line 0: exec: restricted
client: fatal: expected server init string b'SSHUTTLE0001'; got b''
```

So this is when we need to install `python2.7`.

On the jump host:
```
$ sudo apt-get -y update && sudo apt-get -y install python2.7 --no-install-recommends
```

On the client:
```
$ sudo sshuttle --dns --python python2.7 --disable-ipv6 --daemon -r sshuttle@X.X.X.X 0/0
$ sudo ps -fe | grep sshuttle | grep -o '00.*'
00:00:00 logger -p daemon notice -t sshuttle
00:00:00 /usr/bin/python3 /usr/bin/sshuttle --method auto --firewall --syslog
00:00:00 logger -p daemon notice -t sshuttle
00:00:00 ssh sshuttle@X.X.X.X -- 'python2.7' -c 'import sys, os; verbosity=0; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1106), "assembler.py", "exec"))'
00:00:00 /usr/bin/python3 /usr/bin/sshuttle --dns --python python2.7 --disable-ipv6 --daemon -r sshuttle@X.X.X.X 0/0
00:00:00 grep sshuttle
```

No additional configuration needed regarding `rbash` @grrrrr

**Comment by grrrrr** [comment]
@konstruktoid thanks.  Looks like for us the account is additionally restricted with a `$PATH` containing one folder with just a few binaries symlinked into it.

**Comment by konstruktoid** [comment]
This is the configuration, after following the above guide, but a more restricted `$PATH` is recommended. It should be restricted after all.

```
$ ssh sshuttle@X.X.X.X
sshuttle@bifrost:~$ cd ..
-rbash: cd: restricted
sshuttle@bifrost:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
sshuttle@bifrost:~$
```

**Comment by marcinx** [comment]
Hey! Getting the same error but a different origin since updating to MacOS Catalina. Worked fine before:

```
ovacik-pro :: ~ » sudo sshuttle -r root@stellar 0.0.0.0/0 -vv
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.3
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: False
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.8.3
c : connecting to server...
c : executing: ['ssh', '-p', '22', 'root@stellar', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1275), "assembler.py", "exec"))\'"\'"\'\'']
root@stellar's password:
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling u'sshuttle' (7 bytes)
server: assembling u'sshuttle.cmdline_options' (66 bytes)
server: assembling u'sshuttle.helpers' (902 bytes)
server: assembling u'sshuttle.ssnet' (5734 bytes)
server: assembling u'sshuttle.hostwatch' (2463 bytes)
server: assembling u'sshuttle.server' (3673 bytes)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 25, in <module>
  File "sshuttle.server", line 9, in <module>
ImportError: cannot import name which
c : fatal: expected server init string b'SSHUTTLE0001'; got b''
```

Any idea what might be causing this? Python version did not change on server but maybe Catalina's 3.8.3 is to blame?

**Comment by marcinx** [comment]
Hey! Getting the same error but a different origin since updating to MacOS Catalina. Worked fine before:

```
ovacik-pro :: ~ » sudo sshuttle -r root@stellar 0.0.0.0/0 -vv
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.3
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: False
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.8.3
c : connecting to server...
c : executing: ['ssh', '-p', '22', 'root@stellar', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1275), "assembler.py", "exec"))\'"\'"\'\'']
root@stellar's password:
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling u'sshuttle' (7 bytes)
server: assembling u'sshuttle.cmdline_options' (66 bytes)
server: assembling u'sshuttle.helpers' (902 bytes)
server: assembling u'sshuttle.ssnet' (5734 bytes)
server: assembling u'sshuttle.hostwatch' (2463 bytes)
server: assembling u'sshuttle.server' (3673 bytes)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 25, in <module>
  File "sshuttle.server", line 9, in <module>
ImportError: cannot import name which
c : fatal: expected server init string b'SSHUTTLE0001'; got b''
```

Any idea what might be causing this? Python version did not change on server so maybe Catalina is to blame?

**Comment by robhoes** [comment]
I'm also getting this. I think that in my case the server host does not have Python 3, and the following line does not work on Python 2: https://github.com/sshuttle/sshuttle/blob/v1.0.1/sshuttle/server.py#L9

This leads to the `ImportError: cannot import name which` error.

**Comment by kawakamink** [comment]
for me the problem with `ImportError: cannot import name which` was here
[2020-06-17T10:16:07+0900] [ALPM] upgraded sshuttle (0.78.5-2 -> 1.0.1-1)

downgrade solved it

**Comment by ayozemr** [comment]
Had this problem upgrading sshuttle with brew. Reading here tried installing python3 in server and fixed the issue. Better error message would help. Thanks all for guidance in the fix

**Comment by gr33k** [comment]
roar why does this keep happening :( I rely on this app and after every so many updates it breaks. Servers don't tend to always upgrade their versions of Python. While this is great for those that do - it would be ideal for brew packages for osx to retain formulas for old versions so we can easily revert back. It also would be nice for the original code to be more backwards compatible in case the server doesn't have the newest Python version

**Comment by gr33k** [comment]
TIP: git clone the repo - then git checkout an older version. This one worked for me:
git checkout v0.78.5
in that directory I did ./run <my usual sshuttle arguments> and voila!
Really needed this right now, so I'm glad I was able to still do this on my Mojave laptop without too much headache ;)

**Comment by ayozemr** [comment]
> roar why does this keep happening :( I rely on this app and after every so many updates it breaks. Servers don't tend to always upgrade their versions of Python. While this is great for those that do - it would be ideal for brew packages for osx to retain formulas for old versions so we can easily revert back. It also would be nice for the original code to be more backwards compatible in case the server doesn't have the newest Python version

Yes but I would say also... being python 2 deprecated it could be a good moment to start installing python3 on servers and clients that still doesnt have it

**Comment by karna41317** [comment]
@gr33k Thanks for your solution, worked in my case,

**Comment by itamblyn** [comment]
@gr33k also fixed it for me.

Upgrading python on remote server isn't always an option, so thanks for this!!!

**Comment by luckman212** [comment]
@gr33k thanks for your workaround.  Also on Catalina here, and suffering a broken sshuttle for any host with Python2.7 (unfortunately can't upgrade them...)

Has anyone found any other workaround besides cloning the repo and running the old version? I have some scripts/automations set up and its a chore to manually do this for each exception.

**Comment by luckman212** [comment]
Found a workaround that is simpler (for me at least)
maybe it helps someone...

```
mkvirtualenv sshuttle-legacy
pip install sshuttle==0.78.5
ln -s ~/.virtualenvs/sshuttle-legacy/bin/sshuttle /usr/local/bin/sshuttle-legacy
```
Now I can just call **sshuttle-legacy** in any script when the remote side has Py2.x 👍

**Comment by davama** [comment]
@gr33k 
`0.78.5` works for me! Thank you

Local host: Py3.8.3

**Comment by manswizzle** [comment]
I ran into the same issue with the error message and was able to fix it my for my use case.  Maybe this helps somebody:

> c : fatal: expected server init string b'SSHUTTLE0001'; got b''

Backstory:  I've been running sshuttle v0.78.3 for some time on a Xubuntu VM using it to connect to my remote network running an Ubuntu Server 16LTS VM.  Worked beautifully.  Love sshuttle.  This week I changed out the VM for a linux container (lxc/lxd) running Ubuntu Server 18 LTS.  Suddenly, that is when the error began.

Recap:
Local:  Xubuntu 18 LTS VM running sshuttle 0.78.3, python 2.7.17 and python 3.6.9
Old Remote:  Ubuntu Server 16 LTS with python 2.7.12 and python 3.5.2
New Remote:  Ubuntu Server 18 LTS lxc container with python 3.6.9

My journey/solution:
Both the local and new remote ran the same version of python 3.6.9.  On my local machine, I opened up the sshuttle code and the first line is:

`#!/usr/bin/python3`

When I run sshuttle with verbose, I saw the following:

`c : connecting to server...
c : executing: ['ssh', '-p', 'port-number', '-i', '/home/xxx/.ssh/xxx', 'user@remote-ip', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(978), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
`
I noticed that I don't have python 3.5 running on my local machine nor my remote machine.  So then I added the python version option into my shell script/desktop launcher that invokes sshuttle:

`--python python3.6.9`

I still got the error.  Next, I tried it again multiple times with:

`--python python3.6`
`--python python3`

And both worked.  I'm back in business.  I hope this helps somebody else.  Thanks to the sshuttle peeps for an awesome tool!

**Comment by skuhl** [comment]
I think the issue described in the previous comment was fixed with this commit: https://github.com/sshuttle/sshuttle/commit/9b7ce2811ec3ef35b9b7f7dfc157127bc46ece47

**Comment by nitrocode** [comment]
@manswizzle I was able to fix my issue by installing `python3` on my remote host too. I can use `1.0.4` now without having to downgrade to `0.78.5`.

Thanks a lot everyone for the helpful notes.

**Comment by skuhl** [comment]
For those having trouble using sshuttle since their server only has python2 installed, the release notes for the recently released 1.0.5 version indicates that it fixes this problem. It has been fixed in git for some time by pull request #513. I believe python3 is still required on the client machine that you are starting sshuttle from.

**Comment by davama** [comment]
@skuhl 
So the latest release works now?
Thats great!
Ive been using older release.
Will have to try the new code 👍

**Comment by skuhl** [comment]
@davama Try it and report back! It should work (if your problem was that you only had python2 on the server). 

It seems that this issue has morphed into a duplicate of issue #469 (which has to do with Python2 on the server). I'd suggest discussing it on #469. But, maybe some people here are having a different problem?

**Comment by davama** [comment]
Yeah, python3 on client and py2 on server.

will test and report on that ticket.
Thanks!

**Comment by gr33k** [comment]
Awesome news @skuhl - THANK YOU!!!

I will have to test this out also to confirm - need to find one of these old clients. had to pip3 install psutil as well it seems to get it to run, but so far so good.

**Comment by ltagliamonte** [comment]
Gday folks!
I'm currently trying to use sshuttle to build an on demand VPN  style connection for IoT devices.
I'm using ssh certificates and an ephemeral jump hosts (created ondemand):
```
IoT -> jumpHost -> internalService
```
The client process on the IoT device runs in docker container with --net=host and --privileged
jumpHost is an ubuntu container in ECS Fargate that sits in the same network of internalService.

When I try to start the tunnel from IoT device I get the error:
```
c : fatal: expected server init string b'SSHUTTLE0001'; got b''
```

So far, I've read all the issue associated with this error message so far and i still can't get it to work.
Python versions matches on both IoT device and jumpHost:
```
python3 --version
Python 3.8.5
```
and I'm installing latest sshuttle 1.0.5 using pip:
```
sshuttle --version
1.0.5
```
Here the verbose logs from the IoT device, please advice:
```
The operator luigi has requested to open a ssh shuttle tunnel towards 54.215.13.105
['sshuttle', '-vvvvvv', '--python', '/usr/bin/python3', '--dns', '-r', 'aft-hv@54.215.13.105', '172.31.0.0/16', '--ssh-cmd', 'ssh -4 -i /root/.ssh/ssh-key -p 2286 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o CertificateFile=/root/.ssh/ssh-key-cert.pub -o UserKnownHostsFile=/dev/null']
ssh -4 -i /root/.ssh/ssh-key -p 2286 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o CertificateFile=/root/.ssh/ssh-key-cert.pub -o UserKnownHostsFile=/dev/null
SSH shuttle tunnel to 54.215.13.105 started
Starting sshuttle proxy (version 1.0.5).
c : which() could not find 'sudo' in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
fw: Starting firewall with Python version 3.8.5
fw: Selecting a method automatically...
fw: which() found 'iptables' at /usr/sbin/iptables
fw: Method 'nat' was automatically selected.
fw: which() found 'iptables' at /usr/sbin/iptables
fw: ready method name nat.
c : Found DNS servers in /etc/resolv.conf: ['127.0.0.53']
c : Failed to read /run/systemd/resolve/resolv.conf when looking for DNS servers: No such file or directory
c : IPv6 disabled since it isn't supported by method nat.
c : Method: nat
c : IPv4: on
c : IPv6: off (not available with nat method)
c : UDP : off (not available with nat method)
c : DNS : on
c : User: off (available)
c : Subnets to forward through remote host (type, IP, cidr mask width, startPort, endPort):
c :   (<AddressFamily.AF_INET: 2>, '172.31.0.0', 16, 0, 0)
c : Subnets to exclude from forwarding:
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 0, 0)
c : DNS requests normally directed at these servers will be redirected to remote:
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.53')
c : Trying to bind redirector on port 12300
c : TCP redirector listening on ('127.0.0.1', 12300).
c : TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
c : Trying to bind DNS redirector on port 12300
c : Trying to bind DNS redirector on port 12299
c : DNS listening on ('127.0.0.1', 12299).
c : DNS listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12299)>.
c : Starting client with Python version 3.8.5
c : Connecting to server...
c : which() found 'ssh' at /usr/bin/ssh
c : executing: ['/usr/bin/ssh', '-4', '-i', '/root/.ssh/ssh-key', '-p', '2286', '-o', 'LogLevel=ERROR', '-o', 'StrictHostKeyChecking=no', '-o', 'CertificateFile=/root/.ssh/ssh-key-cert.pub', '-o', 'UserKnownHostsFile=/dev/null', 'aft-hv@54.215.13.105', '--', '\'/usr/bin/python3\' -c \'import sys, os; verbosity=6; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1486), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
c : fatal: c : expected server init string b'SSHUTTLE0001'; got b''
```

**Comment by skuhl** [comment]
The latest sshuttle version in git has better reporting when this problem happens and includes tips for solving the problem. Can you try that?

Here is the commit with the change. If you can't use the git version, you can view the "files changed" tab and see the list of tips near the top. #580

Have you tried specifying the path to python on the remote host by passing the --python parameter to sshuttle?

**Comment by ltagliamonte** [comment]
@skuhl thank you for the reply i tried last version and still not luck, same error no suggestions.
Is there a list of server side requirements? the server i'm trying to connect to is a very lean ubuntu Docker image so it maybe be missing some deps.
