### ISSUE TITLE
Connect over jump host

### ISSUE THREAD

**Issue by dominikheinz** [sshuttle/sshuttle#340]
Hello,

I have multiple subnets of VM's and one jumper host.
What I want to achieve is that a person is given the IP of the jumper host and then with sshuttle he establishes a connection and then is forwarded in a dedicated subnet based on the logic of the jumper host. The idea is that the client only knows the IP of the jumper host and when connecting with sshuttle he establishes a connection to the jumper host. The jumper host should then hold a logic that checks the incoming connection and based on the username he redirects the client into one of many dedicated subnets. 

How can I do that with sshuttle. 
Say: The ip of the jumper host is 192.168.1.100 and I have subnets .2 and .3
How can I forward the connection into one of the dedicated subnets over the jumper host?

**Comment by jimilinuxguy** [comment]
Can you accomplish this with -e 'ssh -J user@host1 user@host2' ?

**Comment by superuser5** [comment]
it is very common in the environments to use jump boxes, and this would be a very useful feature.

Example: 
sshuttle -J user@jumpbox.something.com -r user@192.168.0.1

**Comment by hamparawa** [comment]
You can use sshuttle via jump hosts using ssh config. Edit ~/.ssh/config file and add following.

```
Host jump-machine
        Hostname jumpbox.something.com
        User user
Host my-machine
       Hostname 192.168.0.1
       User user
       ProxyJump jump-machine
```

and 
`sshuttle -r my-machine 0/0` should create a vpn to your target machine.

**Comment by alex-phillips** [comment]
I tried this and I get the following output:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 25, in <module>
  File "sshuttle.server", line 9, in <module>
ImportError: cannot import name which
client: fatal: server died with error code 1
```

**Comment by MMquant** [comment]
You can use jumphosts directly in sshuttle command as follows
`sshuttle -r user@lastHost -e 'ssh -J jumpHost1,jumpHost2' <forwardedNetwork>`

**Comment by M-Davies** [comment]
+1 on this, it would be very helpful if this was a thing. The workarounds above are great but it's a nice quality of life change if this was included

**Comment by pfrancks** [comment]
I realized that the jump host via ~/.ssh/config is rather slow. So maybe it would be good if sshuttle has directly a real jump host mode where the optimized code is executed on both, the jump host and the target.
