### ISSUE TITLE
macOS->Alpine: AttributeError: 'MuxWrapper' object has no attribute 'mux'

### ISSUE THREAD

**Issue by ashald** [sshuttle/sshuttle#343]
Hi,

I'm trying to use `sshuttle` from macOS to Alpine and getting the following error (after 1st connection once tunnel established):
```
sshuttle -r 172.20.10.1 0/0 -vv
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.7.3
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: False
User enabled: False
Binding redirector: 12300 12299
TCP redirector listening on ('::1', 12299, 0, 0).
TCP redirector listening with <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12299, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12299).
TCP redirector listening with <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12299)>.
Starting client with Python version 3.7.3
c : connecting to server...
c : executing: ['ssh', '172.20.10.1', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1106), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (66 bytes)
server: assembling 'sshuttle.helpers' (944 bytes)
server: assembling 'sshuttle.ssnet' (5653 bytes)
server: assembling 'sshuttle.hostwatch' (2386 bytes)
server: assembling 'sshuttle.server' (3830 bytes)
Starting server with Python version 3.6.8
 s: latency control setting = True
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s: auto-nets:False
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 8/8
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=7/0)
c : Connected.
c : Waiting: 2 r=[8, 9, 11] w=[11] x=[] (fullness=7/0)
c :   Ready: 2 r=[11] w=[11] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=0
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0', 0, 0), (2, 32, True, '127.0.0.1', 0, 0), (30, 128, True, '::1', 0, 0)]
firewall manager: Got nslist: []
firewall manager: Got ports: 12299,12299,0,0
firewall manager: Got udp: False, user: None
firewall manager: setting up.
firewall manager: setting up IPv6.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle6-12299 -f /dev/stdin
>> pfctl -E
firewall manager: setting up IPv4.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle-12299 -f /dev/stdin
>> pfctl -E
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 2 r=[8, 9, 11] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=7)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c :   Ready: 2 r=[11] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 2 r=[8, 9, 11] w=[] x=[] (fullness=0/0)
c :   Ready: 2 r=[9] w=[] x=[]
c : QUERY_PF_NAT 2,6,172.20.10.4,57010,127.0.0.1,12299
--->  > QUERY_PF_NAT_SUCCESS 72.21.91.70,443
c : Accept TCP: 172.20.10.4:57010 -> 72.21.91.70:443.
c :  > channel=1 cmd=TCP_CONNECT len=17 (fullness=0)
c : new channel: 1
c : Waiting: 3 r=[8, 9, 10, 11] w=[11] x=[] (fullness=17/0)
c :   Ready: 3 r=[10] w=[11] x=[]
c : mux wrote: 25/25
c :  > channel=1 cmd=TCP_DATA len=630 (fullness=17)
c : Waiting: 3 r=[8, 9, 10, 11] w=[11] x=[] (fullness=647/0)
c :   Ready: 3 r=[] w=[11] x=[]
c : mux wrote: 638/638
c : Waiting: 3 r=[8, 9, 10, 11] w=[] x=[] (fullness=647/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=1 cmd=TCP_CONNECT len=17
 s: Connecting to 72.21.91.70:443
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 39, in <module>
  File "sshuttle.server", line 403, in main
  File "sshuttle.ssnet", line 598, in runonce
  File "sshuttle.ssnet", line 486, in callback
  File "sshuttle.ssnet", line 474, in handle
  File "sshuttle.ssnet", line 404, in got_packet
  File "sshuttle.server", line 355, in new_channel
  File "sshuttle.ssnet", line 494, in __init__
  File "sshuttle.ssnet", line 118, in __init__
  File "sshuttle.ssnet", line 91, in _try_peername
OSError: [Errno 9] Bad file descriptor
 s: SW#6:72.21.91.70:443: deleting (1 remain)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "sshuttle.ssnet", line 502, in __del__
  File "sshuttle.ssnet", line 521, in nowrite
AttributeError: 'MuxWrapper' object has no attribute 'mux'
c :   Ready: 3 r=[11] w=[] x=[]
firewall manager: undoing changes.
firewall manager: undoing IPv6 changes.
>> pfctl -a sshuttle6-12299 -F all
>> pfctl -X 14792187875490244057
firewall manager: undoing IPv4 changes.
>> pfctl -a sshuttle-12299 -F all
>> pfctl -X 14792187875490241561
firewall manager: undoing /etc/hosts changes.
c : fatal: server died with error code 1
c :  > channel=1 cmd=TCP_EOF len=0 (fullness=647)
c : SW'unknown':Mux#1: done writing
c : SW'unknown':Mux#1: deleting (1 remain)
c : SW#-1:172.20.10.4:57010: deleting (0 remain)
```

```
$ sshuttle --version
0.78.5
```

I'm pretty sure something is off with my setup - would appreciate any help.
Thanks!

**Comment by geoffreywiseman** [comment]
Just got a similar issue on macOS after losing my connection to a CentOS Server:

```
OSError: [Errno 22] Invalid argument
Exception ignored in: <function MuxWrapper.__del__ at 0x100c118b0>
Traceback (most recent call last):
  File "/usr/local/Cellar/sshuttle/0.78.5_2/libexec/lib/python3.8/site-packages/sshuttle/ssnet.py", line 502, in __del__
  File "/usr/local/Cellar/sshuttle/0.78.5_2/libexec/lib/python3.8/site-packages/sshuttle/ssnet.py", line 521, in nowrite
AttributeError: 'MuxWrapper' object has no attribute 'mux'
```
