### ISSUE TITLE
Something Special about 192.168.156.151?

### ISSUE THREAD

**Issue by larrypl** [sshuttle/sshuttle#344]
Is it me or is there some special handling of this IP address? This just started happening shortly after upgrading to MacOS Catalina (but it worked for a while) and then shortly after replacing cable modem and wireless router hardware (but it worked for a while). And as you can see it doesn't fail with one IP address lower or one higher; just 192.168.156.151/\<anything\> (e.g. 192.168.156.148/31 works; 192.169.156.150/31 fails, 192.168.156.152/31 works. Any range that happens to include 192.168.156.151 fails.)

```
Helios:sshuttle larry$ sshuttle --version
0.78.6.dev7+g935393b
Helios:sshuttle larry$ sshuttle -r remoteid@remotehost 192.168.156.151/32
client: Connected.
Traceback (most recent call last):
  File "/Users/larry/git/sshuttle/INSTALL-0.78.6.dev6+g3e2ad68/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==0.78.6.dev7+g935393b', 'console_scripts', 'sshuttle')()
  File "/Users/larry/git/sshuttle/INSTALL-0.78.6.dev6+g3e2ad68/lib/python3.7/site-packages/sshuttle-0.78.6.dev7+g935393b-py3.7.egg/sshuttle/cmdline.py", line 82, in main
    opt.sudo_pythonpath)
  File "/Users/larry/git/sshuttle/INSTALL-0.78.6.dev6+g3e2ad68/lib/python3.7/site-packages/sshuttle-0.78.6.dev7+g935393b-py3.7.egg/sshuttle/client.py", line 797, in main
    seed_hosts, auto_hosts, auto_nets, daemon, to_nameserver)
  File "/Users/larry/git/sshuttle/INSTALL-0.78.6.dev6+g3e2ad68/lib/python3.7/site-packages/sshuttle-0.78.6.dev7+g935393b-py3.7.egg/sshuttle/client.py", line 551, in _main
    ssnet.runonce(handlers, mux)
  File "/Users/larry/git/sshuttle/INSTALL-0.78.6.dev6+g3e2ad68/lib/python3.7/site-packages/sshuttle-0.78.6.dev7+g935393b-py3.7.egg/sshuttle/ssnet.py", line 599, in runonce
    h.callback(s)
  File "/Users/larry/git/sshuttle/INSTALL-0.78.6.dev6+g3e2ad68/lib/python3.7/site-packages/sshuttle-0.78.6.dev7+g935393b-py3.7.egg/sshuttle/client.py", line 140, in <lambda>
    lambda sock: callback(sock, method, mux, handlers)
  File "/Users/larry/git/sshuttle/INSTALL-0.78.6.dev6+g3e2ad68/lib/python3.7/site-packages/sshuttle-0.78.6.dev7+g935393b-py3.7.egg/sshuttle/client.py", line 366, in onaccept_tcp
    dstip = method.get_tcp_dstip(sock)
  File "/Users/larry/git/sshuttle/INSTALL-0.78.6.dev6+g3e2ad68/lib/python3.7/site-packages/sshuttle-0.78.6.dev7+g935393b-py3.7.egg/sshuttle/methods/pf.py", line 424, in get_tcp_dstip
    peer = sock.getpeername()
OSError: [Errno 22] Invalid argument
Helios:sshuttle larry$ sshuttle -r remoteid@remotehost 192.168.156.150/32
client: Connected.
^Cclient: 
client: Keyboard interrupt: exiting.
Helios:sshuttle larry$ sshuttle -r remoteid@remotehost 192.168.156.152/32
client: Connected.
^Cclient: 
client: Keyboard interrupt: exiting.
```

**Comment by brianmay** [comment]
sshuttle itself doesn't have any special treatment of any IP addresses. It does rely on OS support however, maybe OSX is doing something weird?

The syscall that is failing: We need to know the IP address of the destination of a TCP connection, before we intercepted it, so we can forward the connection to the appropriate host.

**Comment by larrypl** [comment]
That's what I thought, but this is peculiar to this IP address (I did a binary search of a /22 to find out which IP address was causing the “Invalid argument”). It turns out this is one of the IP addresses of an F5 on the other side of the remote host, but there's other F5 IP addresses that don't have this problem, and excluding (“-x”) that single IP address makes the entire 192.168.156.0/22 (what I'm trying to get to) work. (Of course, then I can't get to 192.168.156.151, but I don't need to get to that interface on the F5.)

Seems very strange. I'll do the entire /22 tonight when I get home and with and without excluding 192.168.156.151 and post the results, just to be complete.

**Comment by larrypl** [comment]
Well, I rebooted for other reasons (catalina update) and the problems gone away. Must be something about OSX.
