### ISSUE TITLE
fatal: ['pfctl', '-X', ''] returned 1

### ISSUE THREAD

**Issue by d0u9** [sshuttle/sshuttle#36]
I run sshuttle, but got the error below:

```
Starting sshuttle proxy.
[local sudo] Password:
Starting firewall with Python version 3.5.0
firewall manager ready method name pf.
UDP enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.5.0
c : connecting to server...
c : executing: ['ssh', 'tri=@do6.digital.xyz', '--', 'P=python2; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=2; exec(compile(sys.stdin.read(890), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (8 bytes)
server: assembling 'sshuttle.cmdline_options' (27 bytes)
server: assembling 'sshuttle.helpers' (765 bytes)
server: assembling 'sshuttle.ssnet' (5506 bytes)
server: assembling 'sshuttle.hostwatch' (2307 bytes)
server: assembling 'sshuttle.server' (3016 bytes)
Starting server with Python version 2.7.6
 s: latency control setting = True
 s: available routes:
 s:   2/10.12.0.0/16
 s:   2/10.134.0.0/16
 s:   2/159.203.240.0/20
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=50 (fullness=7)
c : connected.
Connected.
c : Waiting: 2 r=[8, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 2 r=[] w=[9] x=[]
c : mux wrote: 15/15
c : Waiting: 2 r=[8, 9] w=[] x=[] (fullness=7/0)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=57/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=57/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 58/58
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=57/0)
c :   Ready: 2 r=[9] w=[] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=50
Got subnets: [(2, 0, False, '0.0.0.0'), (2, 8, True, '127.0.0.0')]
Got nslist: []
Got ports: 0,12300,0,0
Got udp: False
firewall manager: starting transproxy.
>> pfctl -s all
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=57)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=64/0)
firewall manager: undoing changes.
>> pfctl -a sshuttle -F all
>> pfctl -X
fatal: ['pfctl', '-X', ''] returned 1
c : fatal: cleanup: ['sudo', '-p', '[local sudo] Password: ', 'PYTHONPATH=/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg', '--', '/usr/local/opt/python3/bin/python3.5', '/usr/local/bin/sshuttle', '-v', '-v', '--method', 'auto', '--firewall'] returned 99
```

I run sshuttle with python 3.5.

**Comment by brianmay** [comment]
I am assuming you haven't tried to manually stop sshuttle, right?

To me it looks like something went wrong initializing pfctl (there is a "pfctl -s all" but no "-a sshuttle -f /dev/stdin").

This in turn means sshuttle tries to shutdown the firewall, but this fails, because it didn't get the Xtoken value that should have been setup at the initialization.

This secondary error in turn hides the initial error. Will try to fix the secondary error, so you can see the details from the primary error.

Is this a Python 3.5 specific issue? Does it happen with Python 2.7?

**Comment by d0u9** [comment]
I tried rebooting my computer, but the same issue is still there. I don't know what your "manually stop" means, if reboot is one of this sort. 

I also tried that by reinstalling sshuttle under the python2.7 environment, however, everything works fine.

**Comment by brianmay** [comment]
By manually stop, I mean pushing Ctrl-C or something that would cause the program to exit and try to remove the firewall rules.

Sounds like it is a Python3.5 specific bug.

Are you able to try the latest git version? I put in some changes that will allow us to see what the original error was.

**Comment by d0u9** [comment]
Yes, I am using the latest version of sshuttle. Can you give me some clues about removing the firewall rules?

I am using OSX 10.11.1, `pf` seems be the default firewall.

**Comment by brianmay** [comment]
Please do a git pull, retest, and paste the resultant log here.

**Comment by d0u9** [comment]
The errors seems slightly different:

```
Starting sshuttle proxy.
[local sudo] Password:
firewall manager: Starting firewall with Python version 3.5.0
firewall manager: ready method name pf.
UDP enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.5.0
c : connecting to server...
c : executing: ['ssh', 'tri=@do6.digital.xyz', '--', 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=2; exec(compile(sys.stdin.read(890), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (8 bytes)
server: assembling 'sshuttle.cmdline_options' (27 bytes)
server: assembling 'sshuttle.helpers' (765 bytes)
server: assembling 'sshuttle.ssnet' (5506 bytes)
server: assembling 'sshuttle.hostwatch' (2307 bytes)
server: assembling 'sshuttle.server' (3016 bytes)
Starting server with Python version 2.7.6
 s: latency control setting = True
 s: available routes:
 s:   2/10.12.0.0/16
 s:   2/10.134.0.0/16
 s:   2/159.203.240.0/20
c : connected.
 s:  > channel=0 cmd=PING len=7 (fullness=0)
Connected.
c : Waiting: 2 r=[8, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 2 r=[] w=[9] x=[]
c : mux wrote: 15/15
c : Waiting: 2 r=[8, 9] w=[] x=[] (fullness=7/0)
 s:  > channel=0 cmd=ROUTES len=50 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=57/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=57/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 58/58
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=57/0)
c :   Ready: 2 r=[9] w=[] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=50
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0'), (2, 8, True, '127.0.0.0')]
firewall manager: Got nslist: []
firewall manager: Got ports: 0,12300,0,0
firewall manager: Got udp: False
firewall manager: setting up.
firewall manager: setting up IPv4.
>> pfctl -s all
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> pfctl -a sshuttle -F all
firewall manager: undoing /etc/hosts changes.
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.73', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/__main__.py", line 154, in <module>
    result = firewall.main(opt.method, opt.syslog)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/firewall.py", line 200, in main
    socket.AF_INET, subnets_v4, udp)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/methods/pf.py", line 214, in setup_firewall
    if '\nrdr-anchor "sshuttle" all\n' not in pf_status:
TypeError: a bytes-like object is required, not 'str'
c : fatal: cleanup: ['sudo', '-p', '[local sudo] Password: ', 'PYTHONPATH=/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg', '--', '/usr/local/opt/python3/bin/python3.5', '/usr/local/bin/sshuttle', '-v', '-v', '--method', 'auto', '--firewall'] returned 1
```

**Comment by brianmay** [comment]
I made some changes. Let me know if this fixes for you. If not I will reopen the issue report.

**Comment by d0u9** [comment]
Sorry, it is still not working...  But it now seems like an python syntax error. 

```
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.5.0
firewall manager: ready method name pf.
UDP enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.5.0
c : connecting to server...
c : executing: ['ssh', 'tri-doug@do6.d0u9.xyz', '--', 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=2; exec(compile(sys.stdin.read(890), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (8 bytes)
server: assembling 'sshuttle.cmdline_options' (27 bytes)
server: assembling 'sshuttle.helpers' (765 bytes)
server: assembling 'sshuttle.ssnet' (5506 bytes)
server: assembling 'sshuttle.hostwatch' (2307 bytes)
server: assembling 'sshuttle.server' (3016 bytes)
Starting server with Python version 2.7.6
 s: latency control setting = True
 s: available routes:
 s:   2/10.12.0.0/16
 s:   2/10.134.0.0/16
 s:   2/159.203.240.0/20
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=50 (fullness=7)
c : connected.
Connected.
c : Waiting: 2 r=[8, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 2 r=[] w=[9] x=[]
c : mux wrote: 15/15
c : Waiting: 2 r=[8, 9] w=[] x=[] (fullness=7/0)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=57/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=57/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 58/58
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=57/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=57)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=64/0)
c :   Ready: 2 r=[9] w=[] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=50
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0'), (2, 8, True, '127.0.0.0')]
firewall manager: Got nslist: []
firewall manager: Got ports: 0,12300,0,0
firewall manager: Got udp: False
firewall manager: setting up.
firewall manager: setting up IPv4.
>> pfctl -s all
>> pfctl -a sshuttle -f /dev/stdin
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> pfctl -a sshuttle -F all
firewall manager: undoing /etc/hosts changes.
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.73', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/__main__.py", line 154, in <module>
    result = firewall.main(opt.method, opt.syslog)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/firewall.py", line 200, in main
    socket.AF_INET, subnets_v4, udp)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/methods/pf.py", line 219, in setup_firewall
    pfctl('-a sshuttle -f /dev/stdin', rules)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/methods/pf.py", line 21, in pfctl
    o = p.communicate(stdin)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1068, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1683, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
c : fatal: cleanup: ['sudo', '-p', '[local sudo] Password: ', 'PYTHONPATH=/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg', '--', '/usr/local/opt/python3/bin/python3.5', '/usr/local/bin/sshuttle', '-v', '-v', '--method', 'auto', '--firewall'] returned 1
```

**Comment by brianmay** [comment]
Slowly getting there... These issues should be fixed now. Please test again.

a3fbf860ff0d676fe0cb73325b4487ba3ca31d78

**Comment by d0u9** [comment]
Thx for your patience but the error appears again. 

```
>> pfctl -a sshuttle -f /dev/stdin
>> pfctl -E
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> pfctl -a sshuttle -F all
firewall manager: undoing /etc/hosts changes.
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.73', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/__main__.py", line 154, in <module>
    result = firewall.main(opt.method, opt.syslog)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/firewall.py", line 200, in main
    socket.AF_INET, subnets_v4, udp)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/methods/pf.py", line 228, in setup_firewall
    re.search(r'Token : (.+)', o[1]).group(1)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
c : fatal: cleanup: ['sudo', '-p', '[local sudo] Password: ', 'PYTHONPATH=/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg', '--', '/usr/local/opt/python3/bin/python3.5', '/usr/local/bin/sshuttle', '-v', '-v', '--method', 'auto', '--firewall'] returned 1
```

**Comment by brianmay** [comment]
Arrhhh yes.... I actually thought this line would be a problem so I tested it. However somehow got Python 2.7 by mistake, so it worked. Will fix it.

**Comment by brianmay** [comment]
Should be fixed now. Plus I improved the test cases, so these issues should be auto-detected now.

Please test and let me know.

**Comment by d0u9** [comment]
new error appears
```
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> pfctl -a sshuttle -F all
>> pfctl -X 16110614808320311351
firewall manager: undoing /etc/hosts changes.
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.73', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/__main__.py", line 212, in <module>
    opt.syslog, opt.daemon, opt.pidfile)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/client.py", line 648, in main
    daemon)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/client.py", line 488, in _main
    ssnet.runonce(handlers, mux)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/ssnet.py", line 575, in runonce
    h.callback(s)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/client.py", line 119, in <lambda>
    lambda sock: callback(sock, method, mux, handlers)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/client.py", line 313, in onaccept_tcp
    dstip = method.get_tcp_dstip(sock)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/methods/pf.py", line 160, in get_tcp_dstip
    pfile.write("QUERY_PF_NAT %d,%d,%s,%d,%s,%d\n" % argv)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by brianmay** [comment]
Ok, slowly progressing one error at a time. This one should be fixed now. Please retest.

**Comment by d0u9** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.73', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/__main__.py", line 212, in <module>
    opt.syslog, opt.daemon, opt.pidfile)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/client.py", line 648, in main
    daemon)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/client.py", line 488, in _main
    ssnet.runonce(handlers, mux)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/ssnet.py", line 575, in runonce
    h.callback(s)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/client.py", line 119, in <lambda>
    lambda sock: callback(sock, method, mux, handlers)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/client.py", line 313, in onaccept_tcp
    dstip = method.get_tcp_dstip(sock)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/methods/pf.py", line 164, in get_tcp_dstip
    debug2(b"QUERY_PF_NAT %d,%d,%s,%d,%s,%d" % argv + b' > ' + line)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/helpers.py", line 27, in debug2
    log(s)
  File "/usr/local/lib/python3.5/site-packages/sshuttle-0.73-py3.5.egg/sshuttle/helpers.py", line 12, in log
    sys.stderr.write(logprefix + s)
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by brianmay** [comment]
This should be fixed. Please retest :-)

**Comment by d0u9** [comment]
Bingo! It works. Thanks for your great job! Thanks sincerely!

**Comment by brianmay** [comment]
Great! Glad to hear.

Closing this issue.
