### ISSUE TITLE
adding --dns causes sshuttle to abort

### ISSUE THREAD

**Issue by harishpillay** [sshuttle/sshuttle#386]
[harish@gillman sshuttle]$ ./run --dns -r FQDN:10022 0/0
-c:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
client: Connected.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 41, in <module>
  File "sshuttle.server", line 402, in main
  File "sshuttle.ssnet", line 601, in runonce
  File "sshuttle.ssnet", line 489, in callback
  File "sshuttle.ssnet", line 477, in handle
  File "sshuttle.ssnet", line 411, in got_packet
  File "sshuttle.server", line 361, in dns_req
  File "sshuttle.server", line 179, in __init__
  File "sshuttle.server", line 203, in try_send
OSError: [Errno 101] Network is unreachable
client: fatal: server died with error code 1

But when I remove the --dns, it works just fine. Could you suggest ways I could debug?

**Comment by jrmagers** [comment]
I'm having the same issue on Ubuntu 18, Python 3.6.9.

**Comment by yjftsjthsd-g** [comment]
Any chance you could try installing the current version (`pip install --user` or a virtualenv) and see if that helps? While 0.78.5 is working for me, 0.78.x is *old*.

**Comment by jrmagers** [comment]
> Any chance you could try installing the current version (`pip install --user` or a virtualenv) and see if that helps? While 0.78.5 is working for me, 0.78.x is _old_.

Yes, I pip installed it on Ubuntu 18.04.6 LTS and I can confirm that it (sshuttle 1.1.0) works now.
