### ISSUE TITLE
Error `IndexError: list index out of range` after commit `e320196`

### ISSUE THREAD

**Issue by abelsromero** [sshuttle/sshuttle#412]
I have been using sshuttle directly from master and the after the commit `e320196` it shows the error

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/-/.bin/sshuttle/sshuttle/__main__.py", line 4, in <module>
    sys.exit(main())
  File "/home/-/.bin/sshuttle/sshuttle/cmdline.py", line 85, in main
    return_code = client.main(ipport_v6, ipport_v4,
  File "/home/-/.bin/sshuttle/sshuttle/client.py", line 798, in main
    return _main(tcp_listener, udp_listener, fw, ssh_cmd, remotename,
  File "/home/-/.bin/sshuttle/sshuttle/client.py", line 452, in _main
    (serverproc, serversock) = ssh.connect(
  File "/home/-/.bin/sshuttle/sshuttle/ssh.py", line 100, in connect
    username, password, port, host = parse_hostport(rhostport)
  File "/home/-/.bin/sshuttle/sshuttle/ssh.py", line 84, in parse_hostport
    host = "{}".format(re.split(r'\s*@', rhostport)[1])
IndexError: list index out of range
```

Reberting to the mentiones commit fixes it and I can work again.

**Comment by vBlackOut** [comment]
Hello what is the command line used ? thank

**Comment by abelsromero** [comment]
I can't share as-is because it contains company names, but here it the alias I use replacing the host names.

Each host name has 3 o 4 subdomains, some with dashes (-). Note that the last on the second row has a port range.
```
alias vpnsshuttle='sshuttle --dns -r {MACHINE_HOST} 10/8:443 \
service_hostname:port service_hostname:port service_hostname:port-port \
service_hostname:port service_hostname:port service_hostname:port \
service_hostname:port service_hostname:port service_hostname:port \
service_hostname:port \
service_hostname:port service_hostname:port \
service_hostname:port'
```

**Comment by vBlackOut** [comment]
Your {MACHINE_HOST} is compose :

username@domain ? Or other parameters ?

**Comment by j8r** [comment]
The issue may be port range, like `service_hostname:port-port`.

**Comment by abelsromero** [comment]
Changing to `username@host:port` seems to solve this but then it complains about not finding `sshpass`.
I checked the commits code and I understand the handing of user & password has changed and this is a not-backward compatible change.
Seeing it will break many people's tools and introduces new runtime dependencies, is it posible to make compatible? Like resorting to sshpass and new syntax is done in case of other failures.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/asalgadr/.bin/sshuttle/sshuttle/__main__.py", line 4, in <module>
    sys.exit(main())
  File "/home/asalgadr/.bin/sshuttle/sshuttle/cmdline.py", line 85, in main
    return_code = client.main(ipport_v6, ipport_v4,
  File "/home/asalgadr/.bin/sshuttle/sshuttle/client.py", line 798, in main
    return _main(tcp_listener, udp_listener, fw, ssh_cmd, remotename,
  File "/home/asalgadr/.bin/sshuttle/sshuttle/client.py", line 452, in _main
    (serverproc, serversock) = ssh.connect(
  File "/home/asalgadr/.bin/sshuttle/sshuttle/ssh.py", line 166, in connect
    p = ssubprocess.Popen(argv, stdin=s1a, stdout=s1b, preexec_fn=setup,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sshpass'
```

**Comment by vBlackOut** [comment]
i seach other alternative in python to sshpass 
waiting i just proposal autocomplete password method in progress

**Comment by abelsromero** [comment]
> but the syntax write `username@host:port ` it's better for all user understand network

No objection to that :+1:  you are right.

But the sshpass concerns me, googling I find some mentions of security concerns because it requires storing the password somewhere; file, environment var, etc. Could this be made into a way that the current method of typing in the shell is available? Maybe with a flag?

**Comment by brianmay** [comment]
I have never been really convinced that sshpass is a good idea. ssh already has built in public key authentication for this purpose. However use of sshpass should be optional.

**Comment by j8r** [comment]
Indeed, `ssh-agent` is usually already present, which is an official OpenSSH project that also allows to only write once the passphrase of our encrypted private key.
Then, I don't see the need of `sshpass`, plus this logic doesn't have to be in the sshuttlle project.

**Comment by j8r** [comment]
Indeed, `ssh-agent` is usually already present, which is an official OpenSSH project that also allows to only write once the passphrase of our encrypted private key.
Then, I don't see the need of `sshpass`, plus this logic doesn't have to be in the sshuttle project.

**Comment by brianmay** [comment]
If #418 was merged would this address all the concerns here? I note that sshpass is only required if a password is specified.

**Comment by j8r** [comment]
Don't know, tests should be added to check that.

**Comment by abelsromero** [comment]
Tested https://github.com/sshuttle/sshuttle/pull/418 by @tobigrimm and it seems to be working. But I agree with @j8r that adding tests is important here.
