### ISSUE TITLE
sshuttle master is broken

### ISSUE THREAD

**Issue by matiwinnetou** [sshuttle/sshuttle#49]
I checked out a master version as of today and when I ran this I get an error...

```
[mszczap@d-txl-00445584 sshuttle]$  git:(master)./run -H --dns -r pi@matiwinnetou.no-ip.org 192.168.1.0/24
Python 3.5.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 13, in <module>
TypeError: a bytes-like object is required, not 'str'
client: fatal: server died with error code 1
```

**Comment by matiwinnetou** [comment]
On OSX via brew using 0.72 this works. I also checked that I can work with other ssh hosts just this one fails

**Comment by matiwinnetou** [comment]
```
[mszczap@d-txl-00445584 sshuttle]$  git:(master)./run -vv -H --dns -r pi@matiwinnetou.no-ip.org 192.168.1.0/24
Python 3.5.0
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.5.0
firewall manager: ready method name nat.
UDP enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Binding DNS: 12300
DNS listening on ('127.0.0.1', 12300).
DNS listening with <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.5.0
c : connecting to server...
c : executing: ['ssh', 'pi@matiwinnetou.no-ip.org', '--', 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=2; exec(compile(sys.stdin.read(890), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (7 bytes)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 13, in <module>
TypeError: a bytes-like object is required, not 'str'
c : fatal: server died with error code 1
```

**Comment by vieira** [comment]
What Python version do you have on the server? Have you tried with PR #37?

**Comment by colemickens** [comment]
I'm also seeing this behavior. It's also been included in the latest `sshuttle` release to Arch [community], unfortunately.

```
$ ssh cole@mickens.io -p 222 "python --version"
Python 3.5.1
```

**Comment by colemickens** [comment]
It works after pulling the #37 pull request. Awesome!

**Comment by brianmay** [comment]
Think I have a fix for this and other problems. Just need to setup an Python 3.5 on my server so I can test.
