### ISSUE TITLE
SSHUTTLE no longer working after upgrade

### ISSUE THREAD

**Issue by RmsMit** [sshuttle/sshuttle#499]
I have used sshuttle for a long time (very grateful for this very useful tool) to connect from my Fedora Machines to CentOS services on customers sites in order to access other adjacent customer HW. As of the upgrade to Fedora 32 this no longer works. The Fedora side works fine but the remote CentOS side seems to have issue with assembler.py

`sshuttle -r alexys@wa-myvista-mirrabooka.int.alexys.io 10.212.11.1/16
[local sudo] Password: 
alexys@wa-myvista-mirrabooka.int.alexys.io's password: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 25, in <module>
  File "sshuttle.server", line 9, in <module>
ImportError: cannot import name which
client: fatal: server died with error code 1
`
I have included a more complete trace with more verbose outputs bellow. Nothing else has changed. I suspect that python 3 is now the default on Fedroa side and CentOS is still using Python2.

Any help or pointers you can give me would be much appreciated.

`sshuttle -r alexys@wa-myvista-mirrabooka.int.alexys.io 10.212.11.1/16 -vvv -e "ssh -v"
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.3
firewall manager: ready method name nat.
IPv6 enabled: None
UDP enabled: False
DNS enabled: False
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.8.3
c : connecting to server...
c : executing: ['ssh', '-v', '-p', '22', 'alexys@wa-myvista-mirrabooka.int.alexys.io', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1275), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
OpenSSH_8.3p1, OpenSSL 1.1.1g FIPS  21 Apr 2020
debug1: Reading configuration data /home/rms-mit/.ssh/config
debug1: /home/rms-mit/.ssh/config line 1: Applying options for *.int.alexys.io
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: configuration requests final Match pass
debug1: re-parsing configuration
debug1: Reading configuration data /home/rms-mit/.ssh/config
debug1: /home/rms-mit/.ssh/config line 1: Applying options for *.int.alexys.io
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: Connecting to wa-myvista-mirrabooka.int.alexys.io [10.9.3.142] port 22.
debug1: Connection established.
debug1: identity file /home/rms-mit/.ssh/id_rsa type -1
debug1: identity file /home/rms-mit/.ssh/id_rsa-cert type -1
debug1: identity file /home/rms-mit/.ssh/id_dsa type -1
debug1: identity file /home/rms-mit/.ssh/id_dsa-cert type -1
debug1: identity file /home/rms-mit/.ssh/id_ecdsa type -1
debug1: identity file /home/rms-mit/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/rms-mit/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/rms-mit/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/rms-mit/.ssh/id_ed25519 type 3
debug1: identity file /home/rms-mit/.ssh/id_ed25519-cert type -1
debug1: identity file /home/rms-mit/.ssh/id_ed25519_sk type -1
debug1: identity file /home/rms-mit/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/rms-mit/.ssh/id_xmss type -1
debug1: identity file /home/rms-mit/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to wa-myvista-mirrabooka.int.alexys.io:22 as 'alexys'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:aQjGXn1wydXObwqJhv8uHRHJ69yXnrAI0wa5mO59XkU
debug1: Host 'wa-myvista-mirrabooka.int.alexys.io' is known and matches the ECDSA host key.
debug1: Found key in /home/rms-mit/.ssh/known_hosts:383
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: /home/rms-mit/.ssh/id_rsa 
debug1: Will attempt key: /home/rms-mit/.ssh/id_dsa 
debug1: Will attempt key: /home/rms-mit/.ssh/id_ecdsa 
debug1: Will attempt key: /home/rms-mit/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/rms-mit/.ssh/id_ed25519 ED25519 SHA256:dgjdZE/SiRSmzHufbSbxq8KNvIM8IPg1dZctbgno+jM
debug1: Will attempt key: /home/rms-mit/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/rms-mit/.ssh/id_xmss 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: KCM:)

debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: KCM:)

debug1: Next authentication method: publickey
debug1: Trying private key: /home/rms-mit/.ssh/id_rsa
debug1: Trying private key: /home/rms-mit/.ssh/id_dsa
debug1: Trying private key: /home/rms-mit/.ssh/id_ecdsa
debug1: Trying private key: /home/rms-mit/.ssh/id_ecdsa_sk
debug1: Offering public key: /home/rms-mit/.ssh/id_ed25519 ED25519 SHA256:dgjdZE/SiRSmzHufbSbxq8KNvIM8IPg1dZctbgno+jM
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Trying private key: /home/rms-mit/.ssh/id_ed25519_sk
debug1: Trying private key: /home/rms-mit/.ssh/id_xmss
debug1: Next authentication method: password
alexys@wa-myvista-mirrabooka.int.alexys.io's password: 
debug1: Authentication succeeded (password).
Authenticated to wa-myvista-mirrabooka.int.alexys.io ([10.9.3.142]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANGUAGE = en_GB
debug1: Sending env LANG = en_AU.UTF-8
debug1: Sending command: /bin/sh -c 'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c '"'"'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1275), "assembler.py", "exec"))'"'"''
server: assembling u'sshuttle' (7 bytes)
server: assembling u'sshuttle.cmdline_options' (66 bytes)
server: assembling u'sshuttle.helpers' (902 bytes)
server: assembling u'sshuttle.ssnet' (5734 bytes)
server: assembling u'sshuttle.hostwatch' (2463 bytes)
server: assembling u'sshuttle.server' (3673 bytes)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 25, in <module>
  File "sshuttle.server", line 9, in <module>
ImportError: cannot import name which
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
Transferred: sent 16720, received 3284 bytes, in 0.5 seconds
Bytes per second: sent 30729.1, received 6035.6
debug1: Exit status 1
c : fatal: server died with error code 1
[rms-mit@rmsmit-work ~]$ cat /etc/os-release 
NAME=Fedora
VERSION="32 (Thirty Two)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Thirty Two)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
`

**Comment by RmsMit** [comment]
I think I found the issue. Sorry for the confusion.

Issue is that CentOS server that sshuttle is connecting to does not have python3 installed and in this new Sshuttle it appears support for python2 was dropped.
