### ISSUE TITLE
sshuttle syntax error in kali linux 2020.2

### ISSUE THREAD

**Issue by redhoodie09** [sshuttle/sshuttle#508]
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==1.0.4.dev19+gbe4b081', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.0.4.dev19+gbe4b081-py2.7.egg/sshuttle/cmdline.py", line 5, in <module>
    import sshuttle.client as client
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.0.4.dev19+gbe4b081-py2.7.egg/sshuttle/client.py", line 302
    assert(not re.search(rb'[^-\w\.]', hostname))
                                    ^
SyntaxError: invalid syntax

Tried clean installing it couple of time from github & apt. Getting the same error. Any idea how to fix it?

**Comment by brianmay** [comment]
This is because you need Python >= 3.4. Python 2.7 doesn't understand the 'rb' syntax.
