### ISSUE TITLE
fatal error on macOS when using --dns over "Computer-to-Computer" network

### ISSUE THREAD

**Issue by au5ton** [sshuttle/sshuttle#516]
On macOS, the `/etc/resolv.conf` file is generated dynamically depending on the settings in System Preferences. A weird quirk of that is that when creating a ["Computer-to-Computer network"](https://support.apple.com/en-bn/guide/mac-help/mchl98b9beb6/mac), the `/etc/resolv.conf` file **disappears completely**.

While running a "Computer-to-Computer" network, I get the error below when I use the `--dns` flag with sshuttle. The error does not occur when I run sshuttle _without_ the `--dns` flag, but then none of my DNS queries resolve.

My intended use case was using sshuttle to connect to another device on the "Computer-to-Computer" network.

I haven't looked at how sshuttle works yet, but from what I've read there are other ways to "properly" change DNS settings on macOS that may fix this issue. I'm investigating.

Output:
```
user@hostname ~> sshuttle --dns -r user@remote 0/0
[local sudo] Password: 
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 33, in <module>
    sys.exit(load_entry_point('sshuttle==1.0.4', 'console_scripts', 'sshuttle')())
  File "/usr/local/Cellar/sshuttle/1.0.4/libexec/lib/python3.8/site-packages/sshuttle/cmdline.py", line 85, in main
    return_code = client.main(ipport_v6, ipport_v4,
  File "/usr/local/Cellar/sshuttle/1.0.4/libexec/lib/python3.8/site-packages/sshuttle/client.py", line 577, in main
    nslist += resolvconf_nameservers()
  File "/usr/local/Cellar/sshuttle/1.0.4/libexec/lib/python3.8/site-packages/sshuttle/helpers.py", line 53, in resolvconf_nameservers
    for line in open('/etc/resolv.conf'):
FileNotFoundError: [Errno 2] No such file or directory: '/etc/resolv.conf'
```

/etc/resolv.conf sample while connected directly to an access point:
```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search domain.com
nameserver 192.168.1.123
```

**Comment by au5ton** [comment]
Upon further investigation, the `pf` method doesn't route any traffic when used with "Computer-to-Computer" networks. curl requests to `1.1.1.1` still fail.
