### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by matiwinnetou** [sshuttle/sshuttle#53]
This is a new problem that I am getting connecting to home, version I am using is from master from shuttle/shuttle.

To other ssh servers I can establish a connection, just this one doesn't work.
On server I have Arch Linux (ARM) with Rasperry PI 2

```
[mszczap@d-txl-00445584 sshuttle]$  git:(master) 2Acat home.sh 
#!/bin/bash
./run -vv -H --dns -r pi@matiwinnetou.no-ip.org 192.168.1.0/24
[mszczap@d-txl-00445584 sshuttle]$  git:(master) 2A./home.sh 
Python 3.5.1
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.5.1
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Binding DNS: 12300
DNS listening on ('127.0.0.1', 12300).
DNS listening with <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.5.1
c : connecting to server...
c : executing: ['ssh', 'pi@matiwinnetou.no-ip.org', '--', 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=2; stdin=getattr(sys.stdin,"buffer",sys.stdin); exec(compile(stdin.read(915), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (27 bytes)
server: assembling 'sshuttle.helpers' (861 bytes)
server: assembling 'sshuttle.ssnet' (5502 bytes)
server: assembling 'sshuttle.hostwatch' (2307 bytes)
server: assembling 'sshuttle.server' (3100 bytes)
Starting server with Python version 3.5.1
 s: latency control setting = True
 s: available routes:
 s:   2/192.168.1.0/24
c : Connected.
c : seed_hosts: []
c :  > channel=0 cmd=HOST_REQ len=0 (fullness=7)
c : Waiting: 3 r=[7, 8, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 3 r=[] w=[9] x=[]
c : mux wrote: 15/15
c : mux wrote: 8/8
c : Waiting: 3 r=[7, 8, 9] w=[] x=[] (fullness=7/0)
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=17 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=24/0)
 s:   Ready: 1 r=[] w=[5] x=[]
c :   Ready: 3 r=[9] w=[] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : mux wrote: 15/15
c : Waiting: 3 r=[7, 8, 9] w=[] x=[] (fullness=14/0)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=24/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 25/25
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=24/0)
c :   Ready: 3 r=[9] w=[] x=[]
c : <  channel=0 cmd=ROUTES len=17
firewall manager: Got subnets: [(2, 24, False, '192.168.1.0'), (2, 8, True, '127.0.0.0')]
firewall manager: Got partial nslist: [(2, '10.250.16.37')]
firewall manager: Got partial nslist: [(2, '10.250.16.37'), (2, '10.250.16.38')]
firewall manager: Got partial nslist: [(2, '10.250.16.37'), (2, '10.250.16.38'), (2, '10.243.48.16')]
firewall manager: Got partial nslist: [(2, '10.250.16.37'), (2, '10.250.16.38'), (2, '10.243.48.16'), (2, '10.243.48.222')]
firewall manager: Got nslist: [(2, '10.250.16.37'), (2, '10.250.16.38'), (2, '10.243.48.16'), (2, '10.243.48.222')]
firewall manager: Got ports: 0,12300,0,12300
firewall manager: Got udp: False
firewall manager: setting up.
firewall manager: setting up IPv4.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.1.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
 s:  > channel=0 cmd=PONG len=7 (fullness=24)
 s: <  channel=0 cmd=HOST_REQ len=0
 s: mux wrote: 15/15
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.0/8 -p tcp
HH: Starting hostwatch with Python version 3.5.1
 s: Waiting: 2 r=[4, 7] w=[] x=[] (fullness=31/0)
 s:   Ready: 2 r=[4] w=[] x=[]
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.250.16.37/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: Waiting: 2 r=[4, 7] w=[] x=[] (fullness=0/0)
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.250.16.38/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
HH: Found: 1: 1.186.176.170
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.243.48.16/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
HH: Traceback (most recent call last):
--->   File "sshuttle.server", line 106, in start_hostwatch
--->   File "sshuttle.hostwatch", line 262, in hw_main
--->   File "sshuttle.hostwatch", line 65, in read_host_cache
--->   File "sshuttle.hostwatch", line 79, in found_host
--->   File "sshuttle.hostwatch", line 39, in write_host_cache
---> TypeError: a bytes-like object is required, not 'str'
 s:   Ready: 2 r=[7] w=[] x=[]
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.243.48.222/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 3 r=[7, 8, 9] w=[] x=[] (fullness=0/0)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 36, in <module>
  File "sshuttle.server", line 327, in main
  File "sshuttle.ssnet", line 575, in runonce
  File "sshuttle.server", line 256, in hostwatch_ready
TypeError: Can't convert 'bytes' object to str implicitly
c :   Ready: 3 r=[9] w=[] x=[]
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
firewall manager: undoing /etc/hosts changes.
c : fatal: server died with error code 1
[mszczap@d-txl-00445584 sshuttle]$  git:(master) 2A
```

**Comment by brianmay** [comment]
I have never tested the hostwatch stuff, and not even sure what it does.

Looks like there might be code there that is broken and needs fixing for Python 3. Patches welcome :-)

**Comment by matiwinnetou** [comment]
what do you mean hostwatch stuff?

**Comment by matiwinnetou** [comment]
Yes on both client and server I use python 3.x
