### ISSUE TITLE
Error running sshuttle in Docker container

### ISSUE THREAD

**Issue by dclong** [sshuttle/sshuttle#546]
I run the command `sudo sshuttle -r user@server 0.0.0.0/0 -vv` but got the following error message saying that root permission is need. Notice that I'm running sshuttle inside Docker (Ubuntu LTS) and I have have configured `ProxyCommand` in /root/.ssh/config to visit `server` since it cannot be visited directly. Any insights on what might have caused the problem?
```
ash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
server: assembling 'sshuttle' (88 bytes)
server: assembling 'sshuttle.cmdline_options' (65 bytes)
server: assembling 'sshuttle.helpers' (892 bytes)
server: assembling 'sshuttle.ssnet' (5789 bytes)
server: assembling 'sshuttle.hostwatch' (2466 bytes)
server: assembling 'sshuttle.server' (3675 bytes)
Starting server with Python version 3.6.8
 s: latency control setting = True
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s: auto-nets:False
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
c : Connected.
c : Waiting: 2 r=[5, 8] w=[8] x=[] (fullness=7/0)
c :   Ready: 2 r=[8] w=[8] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 2 r=[5, 8] w=[] x=[] (fullness=14/0)
 s: mux wrote: 8/8
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=7/0)
c :   Ready: 2 r=[8] w=[] x=[]
c : <  channel=0 cmd=ROUTES len=0
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0', 0, 0)]
firewall manager: Got nslist: []
firewall manager: Got ports: 0,12300,0,0
firewall manager: Got udp: False, user: None
firewall manager: setting up.
firewall manager: setting up IPv4.
iptables v1.8.4 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
iptables v1.8.4 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
firewall manager: Error trying to undo IPv4 firewall.
firewall manager: ---> Traceback (most recent call last):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/linux.py", line 27, in ipt_chain_exists
firewall manager: --->     output = ssubprocess.check_output(argv, env=env)
firewall manager: --->   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
firewall manager: --->     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
firewall manager: --->   File "/usr/lib/python3.8/subprocess.py", line 512, in run
firewall manager: --->     raise CalledProcessError(retcode, process.args,
firewall manager: ---> subprocess.CalledProcessError: Command '['iptables', '-t', 'nat', '-nL']' returned non-zero exit status 3.
firewall manager: ---> 
firewall manager: ---> During handling of the above exception, another exception occurred:
firewall manager: ---> 
firewall manager: ---> Traceback (most recent call last):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/firewall.py", line 216, in main
firewall manager: --->     method.setup_firewall(
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/methods/nat.py", line 39, in setup_firewall
firewall manager: --->     self.restore_firewall(port, family, udp, user)
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/methods/nat.py", line 111, in restore_firewall
firewall manager: --->     if ipt_chain_exists(family, table, chain):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/linux.py", line 32, in ipt_chain_exists
firewall manager: --->     raise Fatal('%r returned %d' % (argv, e.returncode))
firewall manager: ---> sshuttle.helpers.Fatal: ['iptables', '-t', 'nat', '-nL'] returned 3
firewall manager: ---> 
firewall manager: ---> During handling of the above exception, another exception occurred:
firewall manager: ---> 
firewall manager: ---> Traceback (most recent call last):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/linux.py", line 27, in ipt_chain_exists
firewall manager: --->     output = ssubprocess.check_output(argv, env=env)
firewall manager: --->   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
firewall manager: --->     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
firewall manager: --->   File "/usr/lib/python3.8/subprocess.py", line 512, in run
firewall manager: --->     raise CalledProcessError(retcode, process.args,
firewall manager: ---> subprocess.CalledProcessError: Command '['iptables', '-t', 'nat', '-nL']' returned non-zero exit status 3.
firewall manager: ---> 
firewall manager: ---> During handling of the above exception, another exception occurred:
firewall manager: ---> 
firewall manager: ---> Traceback (most recent call last):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/firewall.py", line 267, in main
firewall manager: --->     method.restore_firewall(port_v4, socket.AF_INET, udp, user)
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/methods/nat.py", line 111, in restore_firewall
firewall manager: --->     if ipt_chain_exists(family, table, chain):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/linux.py", line 32, in ipt_chain_exists
firewall manager: --->     raise Fatal('%r returned %d' % (argv, e.returncode))
firewall manager: ---> sshuttle.helpers.Fatal: ['iptables', '-t', 'nat', '-nL'] returned 3
firewall manager: undoing /etc/hosts changes.
firewall manager: Error trying to undo /etc/hosts changes.
firewall manager: ---> Traceback (most recent call last):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/linux.py", line 27, in ipt_chain_exists
firewall manager: --->     output = ssubprocess.check_output(argv, env=env)
firewall manager: --->   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
firewall manager: --->     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
firewall manager: --->   File "/usr/lib/python3.8/subprocess.py", line 512, in run
firewall manager: --->     raise CalledProcessError(retcode, process.args,
firewall manager: ---> subprocess.CalledProcessError: Command '['iptables', '-t', 'nat', '-nL']' returned non-zero exit status 3.
firewall manager: ---> 
firewall manager: ---> During handling of the above exception, another exception occurred:
firewall manager: ---> 
firewall manager: ---> Traceback (most recent call last):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/firewall.py", line 216, in main
firewall manager: --->     method.setup_firewall(
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/methods/nat.py", line 39, in setup_firewall
firewall manager: --->     self.restore_firewall(port, family, udp, user)
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/methods/nat.py", line 111, in restore_firewall
firewall manager: --->     if ipt_chain_exists(family, table, chain):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/linux.py", line 32, in ipt_chain_exists
firewall manager: --->     raise Fatal('%r returned %d' % (argv, e.returncode))
firewall manager: ---> sshuttle.helpers.Fatal: ['iptables', '-t', 'nat', '-nL'] returned 3
firewall manager: ---> 
firewall manager: ---> During handling of the above exception, another exception occurred:
firewall manager: ---> 
firewall manager: ---> Traceback (most recent call last):
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/firewall.py", line 279, in main
firewall manager: --->     restore_etc_hosts(port_v6 or port_v4)
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/firewall.py", line 51, in restore_etc_hosts
firewall manager: --->     rewrite_etc_hosts({}, port)
firewall manager: --->   File "/usr/local/lib/python3.8/dist-packages/sshuttle/firewall.py", line 30, in rewrite_etc_hosts
firewall manager: --->     os.link(HOSTSFILE, BAKFILE)
firewall manager: ---> OSError: [Errno 18] Invalid cross-device link: '/etc/hosts' -> '/etc/hosts.sbak'
fatal: ['iptables', '-t', 'nat', '-nL'] returned 3
 s:   Ready: 1 r=[0] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=7)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: mux wrote: 15/15
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=0/0)
c : fatal: cleanup: ['/usr/bin/python3', '/usr/local/bin/sshuttle', '-v', '-v', '--method', 'auto', '--firewall'] returned 99
 s:   Ready: 1 r=[0] w=[] x=[]
```

**Comment by skuhl** [comment]
I don't use Docker, but have you tried this? It is the first link that appears when I search your iptables error message along with the word "docker": https://stackoverflow.com/questions/41706983/installing-iptables-in-docker-container-based-on-alpinelinux

**Comment by dclong** [comment]
Thank you very much, @skuhl! The trick in the stackoverflow discussion helps. I'm still encountering the issue https://github.com/sshuttle/sshuttle/issues/518, but I'm one step closer (to a working solution) now.

**Comment by dclong** [comment]
I've installed `sshuttle` from the master branch which should fix the issue  https://github.com/sshuttle/sshuttle/issues/518. However, it still doesn't work for me. Following is the log messages. 

```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
server: assembling 'sshuttle' (88 bytes)
server: assembling 'sshuttle.cmdline_options' (65 bytes)
server: assembling 'sshuttle.helpers' (892 bytes)
server: assembling 'sshuttle.ssnet' (5789 bytes)
server: assembling 'sshuttle.hostwatch' (2466 bytes)
server: assembling 'sshuttle.server' (3929 bytes)
Starting server with Python version 3.6.8
 s: latency control setting = True
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s: auto-nets:False
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
c : Connected.
c : Waiting: 2 r=[5, 8] w=[8] x=[] (fullness=7/0)
c :   Ready: 2 r=[] w=[8] x=[]
c : mux wrote: 15/15
c : Waiting: 2 r=[5, 8] w=[] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
 s: mux wrote: 8/8
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=7/0)
c :   Ready: 2 r=[8] w=[] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=0
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0', 0, 0), (2, 32, True, '127.0.0.1', 0, 0)]
firewall manager: Got nslist: []
firewall manager: Got ports: 0,12300,0,0
firewall manager: Got udp: False, user: None
firewall manager: setting up.
firewall manager: setting up IPv4.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN -m addrtype --dst-type LOCAL ! -p udp
>> iptables -t nat -A sshuttle-12300 -j RETURN -m addrtype --dst-type LOCAL -p udp ! --dport 53
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 0.0.0.0/0 -p tcp --to-ports 12300 -m ttl ! --ttl 63
c : mux wrote: 15/15
c : Waiting: 2 r=[5, 8] w=[] x=[] (fullness=14/0)
client_loop: send disconnect: Broken pipe
client_loop: send disconnect: Broken pipe
c :   Ready: 2 r=[8] w=[] x=[]
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
c : fatal: ssh connection to server (pid 380) exitedwith returncode 255
```

**Comment by skuhl** [comment]
It did fix the error that I indicated that it would fix. I don't use docker, so I don't think I can help.

**Comment by dclong** [comment]
I tried the same settings in a VM and it works well. So it indeed seems to due to the Docker environment.

**Comment by skuhl** [comment]
The "client_loop: send disconnect: Broken pipe" messages can be caused by not excluding the remote host that you are connecting to. If you specify "-r example.com", you should try to include "-x example.com" so that your SSH connection to example.com does not go through sshuttle. 

Have you tried excluding the remote host?

**Comment by dclong** [comment]
It doesn't help. I still got the same error messages.

**Comment by nikatlas** [comment]
https://github.com/sshuttle/sshuttle/pull/759
Maybe this helps 
hosts file is mounted on a docker container.
