### ISSUE TITLE
[FreeBSD 12.2] --sudoers and --sudoers-user output errors

### ISSUE THREAD

**Issue by willbprog127** [sshuttle/sshuttle#582]
Greetings!  

I'm using FreeBSD 12.2 amd64 with sshuttle 1.0.5 installed from `pip`.  It installed in `/home/will/.local/bin`, so this is where it's run from.  I purposely don't want to include this directory in my PATH right now.

Here is the output of each command:

```
$ /home/will/.local/bin/sshuttle --sudoers
Traceback (most recent call last):
  File "/home/will/.local/bin/sshuttle", line 8, in <module>
    sys.exit(main())
  File "/home/will/.local/lib/python3.7/site-packages/sshuttle/cmdline.py", line 29, in main
    file_name=opt.sudoers_filename
  File "/home/will/.local/lib/python3.7/site-packages/sshuttle/sudoers.py", line 64, in sudoers
    save_config(content, file_name)
  File "/home/will/.local/lib/python3.7/site-packages/sshuttle/sudoers.py", line 40, in save_config
    ], stdout=PIPE, stdin=PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
```
$ /home/will/.local/bin/sshuttle --sudoers --sudoers-user will
Traceback (most recent call last):
  File "/home/will/.local/bin/sshuttle", line 8, in <module>
    sys.exit(main())
  File "/home/will/.local/lib/python3.7/site-packages/sshuttle/cmdline.py", line 29, in main
    file_name=opt.sudoers_filename
  File "/home/will/.local/lib/python3.7/site-packages/sshuttle/sudoers.py", line 64, in sudoers
    save_config(content, file_name)
  File "/home/will/.local/lib/python3.7/site-packages/sshuttle/sudoers.py", line 40, in save_config
    ], stdout=PIPE, stdin=PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
On FreeBSD:
* The `sudo` command, when installed, is at `/usr/local/bin/sudo`
* The `sudoers` file is at: `/usr/local/etc/sudoers`

Thank you! :+1:

**Comment by wmantly** [comment]
`suders` flag only works on Linux hosts.

**Comment by willbprog127** [comment]
> `suders` flag only works on Linux and OSX hosts.

@wmantly Thanks for that.  I didn't see that limitation in the documentation, but I have to admit I didn't read every single thing. :wink:   I eventually used `--sudoers-no-modify` and adjusted that to work.

Will there be a fix to this, or maybe have sshuttle display a message about these functions not working on FreeBSD?

Thanks! :+1:

**Comment by wmantly** [comment]
I wrote it in #269. If remember correctly, the BSD's do no use `visudo` and I am not comfortable editing the sudoers files without validation, especially automatically. If you can suggest a way or make this script validate sudoers file changes for BSD then we can get it in. https://github.com/wmantly/sudoers-add 

Also, it is stated in the docs here that it works for Linux and OSX. https://sshuttle.readthedocs.io/en/stable/usage.html#sudoers-file

**Comment by willbprog127** [comment]
So I guess I'll close it as 'wontfix'?  Thanks for the info, though :+1:
