### ISSUE TITLE
Socket operation on non-socket

### ISSUE THREAD

**Issue by strowk** [sshuttle/sshuttle#596]
I'm running it like this 
```
    sshuttle -r root@<remoteip> --python python3 <localip>/32 
```
and receiving following:

```
client: Connected.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 37, in <module>
  File "sshuttle.server", line 250, in main
  File "/usr/lib/python3.8/socket.py", line 544, in fromfd
    return socket(family, type, proto, nfd)
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 88] Socket operation on non-socket
client: fatal: server died with error code 1
```

Then process exits. How to fix it?

**Comment by brianmay** [comment]
strowk <notifications@github.com> writes:

> I'm running it like this 
> ```
>     sshuttle -r root@<remoteip> --python python3 <localip>/32 
> ```
> and receiving following:

What version of sshuttle were you using?
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by VariableDeclared** [comment]
Seeing this issue with sshuttle 0.78.5 and python 3.8/3.9 on Ubuntu Focal.

My workaround was to request python2 on the remote (`--python python2`)
