### ISSUE TITLE
Ubuntu 21.4 - OSError: [Errno 88] Socket operation on non-socket

### ISSUE THREAD

**Issue by Alex-1357** [sshuttle/sshuttle#662]
I have full workable Python environment:

    #ls my_env
    bin  include  lib  lib64  pyvenv.cfg  share
    #/home/proxyadmin/environments/my_env/bin/python3
    Python 3.9.5 (default, May 11 2021, 08:20:37) 
    [GCC 10.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> exit

I have PIP and other packages

    #sudo apt install -y python3-pip
    #sudo apt install -y build-essential libssl-dev libffi-dev python3-dev

A couple of hours I try to add additional future to start Python correctly like

    #ln --symbolic /usr/bin/python3 /usr/bin/python 

sshutlle must be working, but no:

    [sudo] password for root: 
    Starting sshuttle proxy.
    firewall manager: Starting firewall with Python version 2.7.18
    firewall manager: ready method name nat.
    IPv6 enabled: False
    UDP enabled: False
    DNS enabled: False
    Binding redirector: 12300
    TCP redirector listening on ('127.0.0.1', 12300).
    TCP redirector listening with <socket._socketobject object at 0x7f3db6369280>.
    Starting client with Python version 2.7.18
    c : connecting to server...
    c : executing: ['ssh', 'proxyadmin@xx.xx.xx.xx', '--', '\'/home/proxyadmin/environments/my_env/bin/python3\' -c \'import sys, os;     verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(978), "assembler.py", "exec"))\'']
    c :  > channel=0 cmd=PING len=7 (fullness=0)
    proxyadmin@xx.xx.xx.xx's password: 
    assembler.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    server: assembling 'sshuttle' (7 bytes)
    server: assembling 'sshuttle.cmdline_options' (44 bytes)
    server: assembling 'sshuttle.helpers' (950 bytes)
    server: assembling 'sshuttle.ssnet' (5542 bytes)
    server: assembling 'sshuttle.hostwatch' (2366 bytes)
    server: assembling 'sshuttle.server' (3298 bytes)
    Starting server with Python version 3.9.5
     s: latency control setting = True
     s: available routes:
     s:   2/192.168.4.0/24
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "assembler.py", line 37, in <module>
      File "sshuttle.server", line 250, in main
    c : Connected.
    c : Waiting: 2 r=[4, 8] w=[8] x=[] (fullness=7/0)
    c :   Ready: 2 r=[] w=[8] x=[]
    c : mux wrote: 15/15
    c : Waiting: 2 r=[4, 8] w=[] x=[] (fullness=7/0)
      File "/usr/lib/python3.9/socket.py", line 545, in fromfd
        return socket(family, type, proto, nfd)
      File "/usr/lib/python3.9/socket.py", line 232, in __init__
        _socket.socket.__init__(self, family, type, proto, fileno)
    OSError: [Errno 88] Socket operation on non-socket
    c :   Ready: 2 r=[8] w=[] x=[]
    c : fatal: server died with error code 1

**Comment by brianmay** [comment]
What version of sshuttle is this?

**Comment by skuhl** [comment]
Is python installed on the remote host? If so, have you tried using the --python parameter with sshuttle to tell sshuttle where python is on the remote host?

Similar issues: #596 #523

**Comment by Alex-1357** [comment]
> 
> 
> What version of sshuttle is this?

0.78.1

> 
> 
> Is python installed on the remote host? If so, have you tried using the --python parameter with sshuttle to tell sshuttle where python is on the remote host?
> 
> Similar issues: #596 #523

Of course, I use --python parameters, please see above  --python=/home/proxyadmin/environments/my_env/bin/python3
But this parameter not change error result.

**Comment by skuhl** [comment]
Oops. I missed the parameters.

Have you tried a newer version of sshuttle? I thought Ubuntu 21.04 has sshuttle 1.0.4 in their repo. 0.78.1 was released in 2016. 

Does `ssh proxyadmin@xx.xx.xx.xx -- /home/proxyadmin/environments/my_env/bin/python3 --version` print the version of python on the remote computer?
