### ISSUE TITLE
OSError exception with ssh option

### ISSUE THREAD

**Issue by haha150** [sshuttle/sshuttle#666]
Hi,

i get an exception when trying to use the "-e" command for "-oKexAlgorithms", is this fixable?

> sshuttle -e 'ssh -oKexAlgorithms=+diffie-hellman-group1-sha1' -vvr xxx@10.x.x.x:22000 10.x.x.x/24     
> Starting sshuttle proxy (version 1.0.5).
> c : which() found 'sudo' at /usr/bin/sudo
> fw: Starting firewall with Python version 3.9.2
> fw: which() found 'iptables' at /usr/sbin/iptables
> fw: which() found 'iptables' at /usr/sbin/iptables
> fw: ready method name nat.
> c : IPv6 disabled since it isn't supported by method nat.
> c : Method: nat
> c : IPv4: on
> c : IPv6: off (not available with nat method)
> c : UDP : off (not available with nat method)
> c : DNS : off (available)
> c : User: off (available)
> c : Subnets to forward through remote host (type, IP, cidr mask width, startPort, endPort):
> c :   (<AddressFamily.AF_INET: 2>, '10.2.2.0', 24, 0, 0)
> c : Subnets to exclude from forwarding:
> c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 0, 0)
> c : Trying to bind redirector on port 12300
> c : TCP redirector listening on ('127.0.0.1', 12300).
> c : TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
> c : Starting client with Python version 3.9.2
> c : Connecting to server...
> c : which() found 'ssh' at /usr/bin/ssh
> c : executing: ['/usr/bin/ssh', '-oKexAlgorithms=+diffie-hellman-group1-sha1', '-p', '22000', 'xxx@10.x.x.x', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1486), "assembler.py", "exec"))\'"\'"\'\'']
> c :  > channel=0 cmd=PING len=7 (fullness=0)
> j0hn@10.11.1.252's password: 
>  s: assembling 'sshuttle' (88 bytes)
>  s: assembling 'sshuttle.cmdline_options' (65 bytes)
>  s: assembling 'sshuttle.helpers' (2646 bytes)
> Traceback (most recent call last):
>   File "<string>", line 1, in ?
>   File "assembler.py", line 27, in ?
>   File "sshuttle.helpers", line 97
>     except OSError as e:
>                     ^
> SyntaxError: invalid syntax
> c : fatal: c : server died with error code 1

**Comment by skuhl** [comment]
What version of python is on the remote host?

**Comment by haha150** [comment]
version 2.4.3

**Comment by skuhl** [comment]
That python version is quite old. sshuttle currently uses a notation that was introduced in Python 2.6 on the server. So, I believe either Python 2.6 or 2.7 are the minimum requirements for python on the server. Also, note that it supported even fewer versions in some releases, but I think your version (1.0.5) added support back in for 2.6 or 2.7.

**Comment by hacks2learn** [comment]
FYI - This is still a problem with `Python 3.11.2`

And `sshuttle` was installed using `apt and this is the latest version of `Kali 2023.1`

```
┌──(kali㉿kali)-[~]
└─$ ssh -D 127.0.0.1:1080  -p 22000 -oKexAlgorithms=+diffie-hellman-group1-sha1  -oHostKeyAlgorithms=+ssh-rsa   -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" j0hn@10.11.1.252
Warning: Permanently added '[10.11.1.252]:22000' (RSA) to the list of known hosts.
j0hn@10.11.1.252's password: 
Last login: Sun Apr 16 15:01:02 2023 from 192.168.119.167
[j0hn@timeclock ~]$ exit
logout
Connection to 10.11.1.252 closed.
                                                                                                                                                   
┌──(kali㉿kali)-[~]
└─$ sshuttle -vvv -r j0hn@10.11.1.252:22000 10.2.2.0/24
Starting sshuttle proxy (version 1.1.1).
c : which() could not find 'doas' in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/kali/.local/bin
c : which() found 'sudo' at /usr/bin/sudo
c : Starting firewall manager with command: ['/usr/bin/sudo', '-p', '[local sudo] Password: ', '/usr/bin/env', 'PYTHONPATH=/usr/lib/python3/dist-packages', '/usr/bin/python3', '/usr/bin/sshuttle', '-v', '-v', '-v', '--method', 'auto', '--firewall']
fw: Starting firewall with Python version 3.11.2
fw: Selecting a method automatically...
fw: which() found 'iptables' at /usr/sbin/iptables
fw: Method 'nat' was automatically selected.
fw: which() found 'iptables' at /usr/sbin/iptables
fw: ready method name nat.
c : IPv6 enabled: Using default IPv6 listen address ::1
c : Method: nat
c : IPv4: on
c : IPv6: on
c : UDP : off (not available with nat method)
c : DNS : off (available)
c : User: off (available)
c : Subnets to forward through remote host (type, IP, cidr mask width, startPort, endPort):
c :   (<AddressFamily.AF_INET: 2>, '10.2.2.0', 24, 0, 0)
c : Subnets to exclude from forwarding:
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 0, 0)
c :   (<AddressFamily.AF_INET6: 10>, '::1', 128, 0, 0)
c : Trying to bind redirector on port 12300
c : TCP redirector listening on ('::1', 12300, 0, 0).
c : TCP redirector listening with <socket.socket fd=5, family=10, type=1, proto=0, laddr=('::1', 12300, 0, 0)>.
c : TCP redirector listening on ('127.0.0.1', 12300).
c : TCP redirector listening with <socket.socket fd=7, family=2, type=1, proto=0, laddr=('127.0.0.1', 12300)>.
c : Starting client with Python version 3.11.2
c : Connecting to server...
c : which() found 'ssh' at /usr/bin/ssh
c : executing: ['/usr/bin/ssh', '-p', '22000', 'j0hn@10.11.1.252', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1704), "assembler.py", "exec")); sys.exit(98);\'"\'"\'; exit 97\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
j0hn@10.11.1.252's password: 
                              s: Running server on remote host with /usr/bin/python (version 2.4.3)
                                                                                                    s: assembling 'sshuttle' (88 bytes)
 s: assembling 'sshuttle.cmdline_options' (85 bytes)
 s: assembling 'sshuttle.helpers' (2853 bytes)
Traceback (most recent call last):
                                    File "<string>", line 1, in ?
                                                                   File "assembler.py", line 31, in ?
                                                                                                       File "sshuttle.helpers", line 105
                                                                                                                                            except OSError as e:
                                 ^
                                  SyntaxError: invalid syntax
                                                             c : fatal: server died with error code 1
                                                                                                                                                   
┌──(kali㉿kali)-[~]
└─$ 
```

**Comment by brianmay** [comment]
What version of python is on the *remote host*?

**Comment by hacks2learn** [comment]
old... 2.4.3
```
[j0hn@timeclock ~]$ python -V
Python 2.4.3
```
