### ISSUE TITLE
Setup fails in Ubuntu22.04

### ISSUE THREAD

**Issue by sterni1971** [sshuttle/sshuttle#754]
After clone sshutle I've ot

```
$ sudo ./setup.py install
Traceback (most recent call last):
  File "/home/sternber/GIT/sshuttle/./setup.py", line 29, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.10/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
    ep(self)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 75, in version_keyword
    _assign_version(dist, config)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 51, in _assign_version
    _version_missing(config)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 106, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /home/sternber/GIT/sshuttle.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

```

**Comment by brianmay** [comment]
Wondering if we should just remove setuptools-scm. Goal was to improve bug reports, a copy and paste of the output should show exactly what version is being used. But I can't think of one bug report where this actually happened.

And if setuptools-scm is adding extra hurdles that need to be resolved, it clearly is hindering not helping.

**Comment by skuhl** [comment]
I was able to reproduce this and get the same message as the original poster. When running with the SETUPTOOLS_SCM_DEBUG=1 environment variable set, I see:

`fatal: unsafe repository ('/home/x/tmp/sshuttle' is owned by someone else)\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /home/x/tmp/sshuttle`

It appears that the code tries to run git as root even though the repo is not owned by root. This is not allowed with a recent security update in Git unless it is explicitly identified as a "safe". See https://github.com/pypa/setuptools_scm/issues/707 and https://github.blog/2022-04-12-git-security-vulnerability-announced/

I think having a version number hard-coded in some file that is manually updated before/after a release is more straightforward. Nonetheless, maybe the situation will be fixed in the near future and it isn't worth making a change?

(Also, I think setuptools-scm was included before we added the version number to the ouput in pull request #537. Prior to that, I think it was only used for when the --version parameter was used. I haven't investigated if it might be used elsewhere too).

**Comment by brianmay** [comment]
If somebody wants to create a PR that removes setuptools-scm and maybe adds configuration for something like [bump2version](https://github.com/c4urself/bump2version/) I would seriously consider it.

**Comment by skuhl** [comment]
I think this was fixed in setuptools-scm 7.0.0 and higher. Pull request  #770 should fix this problem in sshuttle.
