### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by zakaria-effyis** [sshuttle/sshuttle#765]
When trying to transparently proxy traffic to the instances inside the private network, 

I get this error
```

  [root@vmi904567 cli-stockholm]# sshuttle -r ubuntu@$BASTION_IP 10.0.0.0/16 --dns  --ssh-cmd 'ssh -i /root/aws/cli-stockholm/aws-ec2'
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sshuttle/cmdline.py", line 100, in main
    return_code = client.main(ipport_v6, ipport_v4,
  File "/usr/local/lib/python3.8/site-packages/sshuttle/client.py", line 953, in main
    raise e
  File "/usr/local/lib/python3.8/site-packages/sshuttle/client.py", line 942, in main
    tcp_listener.bind(lv6, lv4)
  File "/usr/local/lib/python3.8/site-packages/sshuttle/client.py", line 167, in bind
    self.v6.bind(address_v6)
OSError: [Errno 99] Cannot assign requested address
[root@vmi904567 cli-stockholm]#

```

For context purposes, I'm following this [tutorial ](https://www.golinuxcloud.com/setup-kubernetes-cluster-on-aws-ec2/#6_Install_sshutle_to_configure_proxy) to set up a K8S cluster on AWS, and using sshuttle to forward proxy from the bastion node in the public subnet to the K8s cluster in the private subnet

**Comment by skuhl** [comment]
Is this issue the same as #738?  It describes a new improved error message that has been merged in, explains why new people are having this problem, and describes a workaround.

**Comment by zakaria-effyis** [comment]
thanks, it worked with:
```
[root@vmi904567 cli-stockholm]# sshuttle -r ubuntu@$BASTION_IP 10.0.0.0/16 --dns  --ssh-cmd 'ssh -i /root/aws/cli-stockholm/aws-ec2' --disable-ipv6
c : Connected to server.
```
