### ISSUE TITLE
Unknown problem on Linux

### ISSUE THREAD

**Issue by nkts** [sshuttle/sshuttle#80]
So I got another problem, just now on Linux (Fedora 23) box.

```
$ pip install --user git+git://github.com/sshuttle/sshuttle.git
You are using pip version 7.1.0, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+git://github.com/sshuttle/sshuttle.git
  Cloning git://github.com/sshuttle/sshuttle.git to /tmp/pip-ak2T1q-build
Installing collected packages: sshuttle
  Running setup.py install for sshuttle
Successfully installed sshuttle-0.77.3.dev2+ng7875d1b
```

```
$ sshuttle -V
0.77.3.dev2+ng7875d1b
$ python --version
Python 2.7.10
```

```
$ sshuttle -r pi@rpi2.lan 0/0
[local sudo] Password: 
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `exec /bin/sh -c 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=0; stdin=getattr(sys.stdin,"buffer",sys.stdin); exec(compile(stdin.read(915), "assembler.py", "exec"))\'''
client: fatal: server died with error code 1
```

Wondering if this depends on Python 3.x

**Comment by vieira** [comment]
Hello, could you run with -vvv and post the output? It might be the version of python on the server.

**Comment by nkts** [comment]
Dunno if server (Raspberry pi) side has anything to do with this

```
$ sshuttle -vvv -r pi@rpi2.lan 0/0
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.10
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket._socketobject object at 0x7ffa0eb419f0>.
Starting client with Python version 2.7.10
c : connecting to server...
c : executing: ['ssh', 'pi@rpi2.lan', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \\\'import sys; verbosity=3; stdin=getattr(sys.stdin,"buffer",sys.stdin); exec(compile(stdin.read(915), "assembler.py", "exec"))\\\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `exec /bin/sh -c 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=3; stdin=getattr(sys.stdin,"buffer",sys.stdin); exec(compile(stdin.read(915), "assembler.py", "exec"))\'''
c : fatal: server died with error code 1
```

**Comment by vieira** [comment]
Might be something related with 7875d1b. Could you please test with 0.77.2?

**Comment by brianmay** [comment]
Yes, I agree with @vieira. It looks like bash is trying to parse the python code, which it isn't suppose to be doing because that should be quoted.

My shell, zsh, reports ``unmatched '``, so looks like something wrong with the quoting.  Not seeing it myself. Will keep looking.

**Comment by nkts** [comment]
With this version no problems:
```
$ pip install --user git+https://github.com/sshuttle/sshuttle@v0.77.2
You are using pip version 7.1.0, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/sshuttle/sshuttle@v0.77.2
  Cloning https://github.com/sshuttle/sshuttle (to v0.77.2) to /tmp/pip-uHysXz-build
Installing collected packages: sshuttle
  Running setup.py install for sshuttle
Successfully installed sshuttle-0.77.2
$ sshuttle -V
0.77.2
$ 
```

And again to latest:
```
$ pip install --user git+https://github.com/sshuttle/sshuttle
You are using pip version 7.1.0, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/sshuttle/sshuttle
  Cloning https://github.com/sshuttle/sshuttle to /tmp/pip-Or3qvY-build
Installing collected packages: sshuttle
  Running setup.py install for sshuttle
Successfully installed sshuttle-0.77.3.dev2+ng7875d1b
$ sshuttle -vvv -r pi@rpi2.lan 0/0
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.10
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket._socketobject object at 0x7f43f5137f30>.
Starting client with Python version 2.7.10
c : connecting to server...
c : executing: ['ssh', 'pi@rpi2.lan', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \\\'import sys; verbosity=3; stdin=getattr(sys.stdin,"buffer",sys.stdin); exec(compile(stdin.read(915), "assembler.py", "exec"))\\\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `exec /bin/sh -c 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=3; stdin=getattr(sys.stdin,"buffer",sys.stdin); exec(compile(stdin.read(915), "assembler.py", "exec"))\'''
c : fatal: expected server init string 'SSHUTTLE0001'; got ''
```

**Comment by brianmay** [comment]
Hopefully this is fixed now. Fingers crossed.

**Comment by EricoCartmanez** [comment]
I get the same error also with older version:

root@kali:~/.local/bin# ./sshuttle -V
**0.77.2**

```
root@kali:~/.local/bin# ./sshuttle -r user@host 10.10.10.0/24

Traceback (most recent call last):
  File "<string>", line 1, in ?
  File "assembler.py", line 18, in ?
AttributeError: 'unicode' object has no attribute 'rpartition'
client: fatal: server died with error code 1
```
