### ISSUE TITLE
syntax error: invalid syntax, server died with error code 1, sshuttle.helpers?

### ISSUE THREAD

**Issue by scottjl** [sshuttle/sshuttle#800]
Ubuntu 22.04 LTS
Python 3.10.6

sshuttle is crashing out with the following, sorry if the formatting is bad, I had to remove a ton of weird line breaks. Can anyone help me fix this?

```
$ sshuttle -r user@host 157.240.0.0/16 31.13.0.0/16 -x 10.0.0.0/20 -vvv
Starting sshuttle proxy (version 1.0.5).
c : which() found 'sudo' at /usr/bin/sudo
fw: Starting firewall with Python version 3.10.6
fw: Selecting a method automatically...
fw: which() found 'iptables' at /usr/sbin/iptables
fw: Method 'nat' was automatically selected.
fw: which() found 'iptables' at /usr/sbin/iptables
fw: ready method name nat.
c : IPv6 disabled since it isn't supported by method nat.
c : Method: nat
c : IPv4: on
c : IPv6: off (not available with nat method)
c : UDP : off (not available with nat method)
c : DNS : off (available)
c : User: off (available)
c : Subnets to forward through remote host (type, IP, cidr mask width, startPort, endPort):
c :   (<AddressFamily.AF_INET: 2>, '157.240.0.0', 16, 0, 0)
c :   (<AddressFamily.AF_INET: 2>, '31.13.0.0', 16, 0, 0)
c : Subnets to exclude from forwarding:
c :   (<AddressFamily.AF_INET: 2>, '10.0.0.0', 20, 0, 0)
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 0, 0)
c : Trying to bind redirector on port 12300
c : TCP redirector listening on ('127.0.0.1', 12300).
c : TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
c : Starting client with Python version 3.10.6
c : Connecting to server...
c : which() found 'ssh' at /usr/bin/ssh
c : executing: ['/usr/bin/ssh', 'user@host', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1486), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
user@host's password: 
s: assembling 'sshuttle' (88 bytes)
s: assembling 'sshuttle.cmdline_options' (65 bytes)
s: assembling 'sshuttle.helpers' (2646 bytes)
Traceback (most recent call last):
File "<string>", line 1, in ?
File "assembler.py", line 27, in ?
File "sshuttle.helpers", line 97
except OSError as e:
^
SyntaxError: invalid syntax
c : fatal:
c : server died with error code 1
```

**Comment by brianmay** [comment]
What version of Python is on the server?

**Comment by scottjl** [comment]
2.4.3.

i'm able to connect from an old ubuntu 18.04 instance running sshuttle 0.78.3, but i'd prefer to use the modern system instead.

**Comment by brianmay** [comment]
So old? Python 2.4.3 was released 2006.

Like it or not, I thing there is a limit to how long we can support really old unsupported versions of Python...

**Comment by scottjl** [comment]
unfortunately the far end is not under my control. but i'm confused, why does the remote end's version matter? why does it work with 0.78.3 but not 1.0.5? the error says syntax error, is this a bug that can be fixed?

**Comment by brianmay** [comment]
sshuttle works by running Python code on the server.

The syntax error is because the old version of Python doesn't understand the modern syntax for declaring an exception handler (use `,` instead of `as`). But IIRC modern versions of Python won't recognise the older deprecated way of declaring an exception handler either.
