### ISSUE TITLE
не понимаю

### ISSUE THREAD

**Issue by replicatedublos** [sshuttle/sshuttle#841]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-14' coro=<Dispatcher._process_polling_updates() done, defined a
\dispatcher.py:407> exception=UnboundLocalError("cannot access local variable 'signup' where it i
Traceback (most recent call last):
  File "C:\Users\replicatedublos\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogra
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\replicatedublos\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogra
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\replicatedublos\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogra
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\replicatedublos\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogra
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\replicatedublos\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogra
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\replicatedublos\Desktop\Новая папка\main.py", line 33, in bot_message
    if db.get_signup(message.from_user.id) == "setnickname":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\replicatedublos\Desktop\Новая папка\db.py", line 21, in get_signup
    return signup
           ^^^^^^
UnboundLocalError: cannot access local variable 'signup' where it is not associated with a value

**Comment by replicatedublos** [comment]
import logging
from aiogram import Bot, types
from aiogram.dispatcher import Dispatcher
from aiogram.utils import executor
import markups as nav
from db import Database

TOKEN = "5730827563:AAHSQf_s-ltRVIqt4FL9oFzwVx22D8FNUh8"

logging.basicConfig(level=logging.INFO)

bot = Bot(token=TOKEN)
dp = Dispatcher(bot)

db = Database('database.db')

@dp.message_handler(commands=['start'])
async def start(message: types.Message):
    if(not db.user_exists(message.from_user.id)):
        db.add_user(message.from_user.id)
        await bot.send_message(message.from_user.id, "Пожалуйста,Укажите ваш nickname")
    else:
        await bot.send_message(message.from_user.id, "Вы уже зарегистрированы!", reply_markup=nav.mainMenu)


@dp.message_handler()
async def bot_message(message: types.Message):
    if message.chat.type == 'private':
        if message.text == '📖 ПРОФИЛЬ':
            pass

        else:
            if db.get_signup(message.from_user.id) == "setnickname":
                if(len(message.text) > 15):
                    await bot.send_message(message.from_user.id, "Никнейм не должен привышать 15 символов!")
                elif '@' in message.text or '/' in message.text:
                    await bot.send_message(message.from_user.id, "Вы ввели запрещённый символ!")
                else:
                    db.set_nickname(message.from_user.id, message.text)
                    db.set_signup(message.from_user.id, "done")
                    await bot.send_message(message.from_user.id, "Регистрация прошла успешно!", reply_markup=nav.mainMenu)
            else:
                await bot.send_message(message.from_user.id, "Мы не понимаем чего вы хотите!")




if __name__ == "__main__":
    executor.start_polling(dp, skip_updates = True)

**Comment by brianmay** [comment]
Not sure how this related to sshuttle...
