### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by ragnarokme** [sshuttle/sshuttle#861]
hi, I'm a beginner and I need a proxy, I installed sshuttle but I can't figure out how to configure it? I am executing in the terminal:
sshuttle -r root@IP:55*** -x IP 0/0 -v --dns
sshuttle -r root@IP:22 -x IP 0/0 -v --dns
and I get an answer

[code] 
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==1.1.1', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.1.1-py2.7.egg/sshuttle/cmdline.py", line 4, in <module>
    import sshuttle.client as client
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.1.1-py2.7.egg/sshuttle/client.py", line 12, in <module>
    import sshuttle.ssh as ssh
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.1.1-py2.7.egg/sshuttle/ssh.py", line 7, in <module>
    import importlib.util
ImportError: No module named util

[/code]

how to fix and make it work? I need for the browser

**Comment by brianmay** [comment]
I think you need Python version >= 3.8, it looks like you have Python 2.7

**Comment by ragnarokme** [comment]
jeka@htpc:~$ ls /usr/bin | grep python
pybabel-python3
python3
python3.10

**Comment by brianmay** [comment]
I don't know what is wrong, but if you look at the stack trace it is clearly showing Python 2.7 - `/usr/local/lib/python2.7/`

**Comment by MattStr11** [comment]
> hi, I'm a beginner and I need a proxy, I installed sshuttle but I can't figure out how to configure it? I am executing in the terminal: sshuttle -r root@IP:55*** -x IP 0/0 -v --dns sshuttle -r root@IP:22 -x IP 0/0 -v --dns and I get an answer
> 
> [code] Traceback (most recent call last): File "/usr/local/bin/sshuttle", line 11, in load_entry_point('sshuttle==1.1.1', 'console_scripts', 'sshuttle')() File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2852, in load_entry_point return ep.load() File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2443, in load return self.resolve() File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2449, in resolve module = **import**(self.module_name, fromlist=['**name**'], level=0) File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.1.1-py2.7.egg/sshuttle/cmdline.py", line 4, in import sshuttle.client as client File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.1.1-py2.7.egg/sshuttle/client.py", line 12, in import sshuttle.ssh as ssh File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.1.1-py2.7.egg/sshuttle/ssh.py", line 7, in import importlib.util ImportError: No module named util
> 
> [/code]
> 
> how to fix and make it work? I need for the browser

 sudo pip3 install sshuttle

try that
