### ISSUE TITLE
ipv6 disabled in kernel, sshuttle breaking

### ISSUE THREAD

**Issue by perfecto25** [sshuttle/sshuttle#865]
reopening issue related to this

https://github.com/sshuttle/sshuttle/issues/303

```
sshuttle -v  -r mrxmini2 192.168.56.0/24
Starting sshuttle proxy (version 1.1.1).
c : Starting firewall manager with command: ['/usr/bin/sudo', '-p', '[local sudo] Password: ', '/usr/bin/env', 'PYTHONPATH=/home/mreider/.local/lib/python3.10/site-packages', '/usr/bin/python3', '/usr/local/bin/sshuttle', '-v', '--method', 'auto', '--firewall']
fw: Starting firewall with Python version 3.10.6
fw: ready method name nat.
c : IPv6 enabled: Using default IPv6 listen address ::1
c : Method: nat
c : IPv4: on
c : IPv6: on
c : UDP : off (not available with nat method)
c : DNS : off (available)
c : User: off (available)
c : Subnets to forward through remote host (type, IP, cidr mask width, startPort, endPort):
c :   (<AddressFamily.AF_INET: 2>, '192.168.56.0', 24, 0, 0)
c : Subnets to exclude from forwarding:
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 0, 0)
c :   (<AddressFamily.AF_INET6: 10>, '::1', 128, 0, 0)

Traceback (most recent call last):
 
 File "/usr/local/bin/sshuttle", line 8, in <module>
 sys.exit(main())
File "/home/mreider/.local/lib/python3.10/site-packages/sshuttle/cmdline.py", line 89, in main
return_code = client.main(ipport_v6, ipport_v4,
File "/home/mreider/.local/lib/python3.10/site-packages/sshuttle/client.py", line 973, in main
                                                                        raise e
File "/home/mreider/.local/lib/python3.10/site-packages/sshuttle/client.py", line 962, in main
tcp_listener.bind(lv6, lv4)
File "/home/mreider/.local/lib/python3.10/site-packages/sshuttle/client.py", line 166, in bind
                        self.v6 = socket.socket(socket.AF_INET6, self.type, self.proto)
 
 File "/usr/lib/python3.10/socket.py", line 232, in __init__
_socket.socket.__init__(self, family, type, proto, fileno)
 OSError: [Errno 97] Address family not supported by protocol

```

running on ubuntu 22, python 3.10, sshuttle 1.1.1

Im guessing the ipv6 check is only checking for presence of sysctl values, which dont exist since I have it disabled in grub

```
 GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 ipv6.disable=1"

```

```
sudo sysctl -a | grep ipv6

... no values
```

ipv6 is definitely disabled though

```
 cat /sys/module/ipv6/parameters/disable
1
```

will try to check the logic

**Comment by perfecto25** [comment]
workaround is to use 

```
sshuttle -r <relay> <IP> --disable-ipv6
```

**Comment by skuhl** [comment]
This is similar to #738 which tried to print an error message suggesting that you should use --disable-ipv6 when problems occurred. However, that fix doesn't appear to be working in your case.

**Comment by abhisheky2095** [comment]
My sshuttle client is python 3.6.8  and Remote server python version is 3.9.18.  And my sshuttle version is 1.1.0 .
And my sshuttle is not working and not able to connect to any service.

this is sshuttle with -vv option is coming 


fw: Starting firewall with Python version 3.9.14
fw: which() found 'iptables' at /usr/sbin/iptables
fw: which() found 'iptables' at /usr/sbin/iptables
fw: ready method name nat.
c : IPv6 enabled: Using default IPv6 listen address ::1
c : Method: nat
c : IPv4: on
c : IPv6: on
c : UDP : off (not available with nat method)
c : DNS : off (available)
c : User: off (available)
c : Subnets to forward through remote host (type, IP, cidr mask width, startPort, endPort):
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 0, 0)
c : Subnets to exclude from forwarding:
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 22, 22)
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 8050, 8050)
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 8001, 8001)
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 9001, 9001)
c :   (<AddressFamily.AF_INET6: 10>, '::1', 128, 0, 0)
c : Trying to bind redirector on port 12300
c : TCP redirector listening on ('::1', 12300, 0, 0).
c : TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
c : TCP redirector listening on ('127.0.0.1', 12300).
c : TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
c : Starting client with Python version 3.9.14
c : Connecting to server...
c : which() found 'ssh' at /usr/bin/ssh
c : executing: ['/usr/bin/ssh', 'seceon@192.168.19.220', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.
fdopen(0, "rb"); exec(compile(sys.stdin.read(1704), "assembler.py", "exec")); sys.exit(98);\'"\'"\'; exit 97\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
 s: Running server on remote host with /usr/bin/python3 (version 3.6.8)
 s: assembling 'sshuttle' (88 bytes)
 s: assembling 'sshuttle.cmdline_options' (85 bytes)
 s: assembling 'sshuttle.helpers' (2853 bytes)
 s: assembling 'sshuttle.ssnet' (5805 bytes)
 s: assembling 'sshuttle.hostwatch' (2522 bytes)
 s: assembling 'sshuttle.server' (3789 bytes)
 s: latency control setting = True
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s: auto-nets:False
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
 s: mux wrote: 8/8
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=7/0)
c : Connected to server.
c : Waiting: 2 r=[5, 7, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 2 r=[9] w=[9] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)

fw: Got subnets: [(2, 32, False, '127.0.0.1', 0, 0), (2, 32, True, '127.0.0.1', 22, 22), (2, 32, True, '127.0.0.1', 8050, 8050), (2, 32, True, '127.0.0.1', 8001, 8001), (2, 32, True, '




Please let me know what is the solution of this?
