### ISSUE TITLE
sshuttle in a virtualbox debian:jessie

### ISSUE THREAD

**Issue by drsect0r** [sshuttle/sshuttle#88]
I want to use sshuttle in a virtual machine box as described here: https://coderwall.com/p/adfxgw/sshuttle-on-windows

Can somebody spot what I'm doing wrong? 

``` shell
$ git clone https://github.com/sshuttle/sshuttle.git
$ cd sshuttle/
$ apt-get install python-setuptools
$ ./setup.py install
$ sshuttle -V
0.78.0

$ sshuttle -l 0.0.0.0 -x 10.0.0.0/8 -x 192.168.0.0/16 0/0
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.78.0', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.0-py2.7.egg/sshuttle/cmdline.py", line 74, in main
    opt.daemon, opt.pidfile)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.0-py2.7.egg/sshuttle/client.py", line 716, in main
    seed_hosts, auto_nets, daemon)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.0-py2.7.egg/sshuttle/client.py", line 421, in _main
    options=dict(latency_control=latency_control))
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.0-py2.7.egg/sshuttle/ssh.py", line 132, in connect
    close_fds=True, stderr=stderr)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by naclander** [comment]
Does this error happen regardless of which directory you are trying to run sshuttle from? i.e. if you `cd ~/' and run sshuttle do you get the same error?

**Comment by drsect0r** [comment]
@naclander thanks for your response, I will need to check on Monday.

**Comment by brianmay** [comment]
Check to make sure you have ssh installed.

**Comment by drsect0r** [comment]
@brianmay SSH is installed
``` shell
$ ssh -V
OpenSSH_6.7p1 Debian-5+deb8u1, OpenSSL 1.0.1k 8 Jan 2015
```

@naclander I do get the same error, regardless in what directory i'm currently in. 
``` shell
$ sshuttle -V
0.78.1.dev1+ng89c5b57

$ sshuttle -l 0.0.0.0 -x 10.0.0.0/8 -x 192.168.0.0/16 0/0
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.78.1.dev1-ng89c5b57', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/cmdline.py", line 74, in main
    opt.daemon, opt.pidfile)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/client.py", line 716, in main
    seed_hosts, auto_nets, daemon)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/client.py", line 421, in _main
    options=dict(latency_control=latency_control))
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/ssh.py", line 132, in connect
    close_fds=True, stderr=stderr)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

$ cd ~/
$ sshuttle -l 0.0.0.0 -x 10.0.0.0/8 -x 192.168.0.0/16 0/0
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.78.1.dev1-ng89c5b57', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/cmdline.py", line 74, in main
    opt.daemon, opt.pidfile)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/client.py", line 716, in main
    seed_hosts, auto_nets, daemon)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/client.py", line 421, in _main
    options=dict(latency_control=latency_control))
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/ssh.py", line 132, in connect
    close_fds=True, stderr=stderr)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

$ sshuttle -V
0.78.1.dev1+ng89c5b57
```

**Comment by brianmay** [comment]
Please run sshuttle in verbose mode; ``-vvv`` should do this.

It does appear to be a problem running ssh; verbose mode should show the command line it is attempting to execute.

**Comment by drsect0r** [comment]
@brianmay I hope this is helpful.

```
$ sshuttle -V
0.78.1.dev1+ng89c5b57

$ sshuttle -vvv -l 0.0.0.0 -x 10.0.0.0/8 -x 192.168.0.0/16 0/0 
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.9
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
Binding redirector: 12300
TCP redirector listening on ('0.0.0.0', 12300).
TCP redirector listening with <socket._socketobject object at 0x7f2de8045130>.
Starting client with Python version 2.7.9
c : connecting to server...
c : executing: ['-vvv', '-c', 'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(958), "assembler.py", "exec"))']
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.78.1.dev1-ng89c5b57', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/cmdline.py", line 74, in main
    opt.daemon, opt.pidfile)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/client.py", line 716, in main
    seed_hosts, auto_nets, daemon)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/client.py", line 421, in _main
    options=dict(latency_control=latency_control))
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.1.dev1_ng89c5b57-py2.7.egg/sshuttle/ssh.py", line 132, in connect
    close_fds=True, stderr=stderr)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by brianmay** [comment]
Yes, that does help.

I note that you have not specified the ``-r`` parameter. Was this really what you intended? So we shouldn't be trying to run ssh or connect to a remote host.

Looks like it is trying to execute "-vvv".  I suspect this is a bug specific to when you haven't supplied the ``-r`` parameter. There is a reference in the code to ``sys.argv[1]`` which I suspect is broken.

**Comment by brianmay** [comment]
I will continue looking at this more tomorrow (assuming nobody else has a fix by then).

**Comment by vieira** [comment]
@brianmay Your suspicion was correct. On older versions the sshuttle shell script would call python with something like `exec python2 "$DIR/main.py" python2 "$@"` so `argv[1]` would be, e.g., `python2`. The new run script no longer does this. Instead it uses something like `exec python2.7 -m "sshuttle" "$@` so `argv[1]` would be the first option being passes, e.g., `-l` or `-vvv`.

In #91 I use sys.executable to get the python executable being used. As always, any comments are welcome.
