### ISSUE TITLE
socket.error: [Errno 101] Network is unreachable when --dns option is on.

### ISSUE THREAD

**Issue by d0u9** [sshuttle/sshuttle#89]
if enable `--dns` option, error `socket.error: [Errno 101] Network is unreachable` is reported. However, if I disable `--dns`, it seems work properly.

**Comment by naclander** [comment]
What version of sshuttle are you using, and what OS?

**Comment by d0u9** [comment]
sshuttle 0.78.0 installed via pip3, OS: ubuntu 14.04 


And here is the log:

```
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Binding DNS: 12300
DNS listening on ('127.0.0.1', 12300).
DNS listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.5.1
c : connecting to server...
c : executing: ['ssh', 'tri-doug@v4.d0u9.xyz', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(958), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling u'sshuttle' (7 bytes)
server: assembling u'sshuttle.cmdline_options' (27 bytes)
server: assembling u'sshuttle.helpers' (949 bytes)
server: assembling u'sshuttle.ssnet' (5540 bytes)
server: assembling u'sshuttle.hostwatch' (2361 bytes)
server: assembling u'sshuttle.server' (3091 bytes)
Starting server with Python version 2.7.6
 s: latency control setting = True
 s: available routes:
 s:   2/45.32.44.0/22
 s:   2/169.254.169.254/32
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=37 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=44/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=44/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 45/45
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=44/0)
c : Connected.
c : Waiting: 3 r=[5, 7, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 3 r=[9] w=[9] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=37
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0'), (2, 8, True, '127.0.0.1')]
firewall manager: Got partial nslist: [(2, '127.0.1.1')]
firewall manager: Got nslist: [(2, '127.0.1.1')]
firewall manager: Got ports: 0,12300,0,12300
firewall manager: Got udp: False
firewall manager: setting up.
firewall manager: setting up IPv4.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/8 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 0.0.0.0/0 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 127.0.1.1/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 3 r=[5, 7, 9] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=44)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=51/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c :   Ready: 3 r=[9] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 3 r=[5, 7, 9] w=[] x=[] (fullness=0/0)
c :   Ready: 3 r=[7] w=[] x=[]
c : Accept UDP using recvfrom.
c : DNS request from ('127.0.0.1', 44094) to None: 32 bytes
c :  > channel=1 cmd=DNS_REQ len=32 (fullness=0)
c : Remaining DNS requests: 1
c : Remaining UDP channels: 0
c : Waiting: 3 r=[5, 7, 9] w=[9] x=[] (fullness=32/0)
c :   Ready: 3 r=[5] w=[9] x=[]
c : mux wrote: 40/40
c : Accept TCP: 192.168.1.131:39970 -> 202.108.23.152:80.
c :  > channel=2 cmd=TCP_CONNECT len=19 (fullness=32)
c : creating new SockWrapper (1 now exist)
c : new channel: 2
c : creating new SockWrapper (2 now exist)
c : Remaining DNS requests: 1
c : Remaining UDP channels: 0
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : Waiting: 4 r=[5, 7, 8, 9] w=[9] x=[] (fullness=51/0)
c :   Ready: 4 r=[] w=[9] x=[]
c : mux wrote: 27/27
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : Waiting: 4 r=[5, 7, 8, 9] w=[] x=[] (fullness=51/0)
c :   Ready: 4 r=[5] w=[] x=[]
c : Accept TCP: 192.168.1.131:39972 -> 202.108.23.152:80.
c :  > channel=3 cmd=TCP_CONNECT len=19 (fullness=51)
c : creating new SockWrapper (3 now exist)
c : new channel: 3
c : creating new SockWrapper (4 now exist)
c : Remaining DNS requests: 1
c : Remaining UDP channels: 0
c : Waiting: 5 r=[5, 7, 8, 9, 10] w=[9] x=[] (fullness=70/0)
c :   Ready: 5 r=[5, 7] w=[9] x=[]
c : mux wrote: 27/27
c : Accept TCP: 192.168.1.131:39974 -> 202.108.23.152:80.
c :  > channel=4 cmd=TCP_CONNECT len=19 (fullness=70)
c : creating new SockWrapper (5 now exist)
c : new channel: 4
c : creating new SockWrapper (6 now exist)
c : Remaining DNS requests: 1
c : Remaining UDP channels: 0
c : Accept UDP using recvfrom.
c : DNS request from ('127.0.0.1', 27686) to None: 28 bytes
c :  > channel=5 cmd=DNS_REQ len=28 (fullness=89)
c : Remaining DNS requests: 2
c : Remaining UDP channels: 0
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : Waiting: 6 r=[5, 7, 8, 9, 10, 11] w=[9] x=[] (fullness=117/0)
c :   Ready: 6 r=[7] w=[9] x=[]
c : mux wrote: 27/27
c : mux wrote: 36/36
c : Accept UDP using recvfrom.
c : DNS request from ('127.0.0.1', 14352) to None: 47 bytes
c :  > channel=6 cmd=DNS_REQ len=47 (fullness=117)
c : Remaining DNS requests: 3
c : Remaining UDP channels: 0
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : Waiting: 6 r=[5, 7, 8, 9, 10, 11] w=[9] x=[] (fullness=164/0)
c :   Ready: 6 r=[7] w=[9] x=[]
c : mux wrote: 55/55
c : Accept UDP using recvfrom.
c : DNS request from ('127.0.0.1', 53597) to None: 31 bytes
c :  > channel=7 cmd=DNS_REQ len=31 (fullness=164)
c : Remaining DNS requests: 4
c : Remaining UDP channels: 0
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : Waiting: 6 r=[5, 7, 8, 9, 10, 11] w=[9] x=[] (fullness=195/0)
c :   Ready: 6 r=[7] w=[9] x=[]
c : mux wrote: 39/39
c : Accept UDP using recvfrom.
c : DNS request from ('127.0.0.1', 63949) to None: 38 bytes
c :  > channel=8 cmd=DNS_REQ len=38 (fullness=195)
c : Remaining DNS requests: 5
c : Remaining UDP channels: 0
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : Waiting: 6 r=[5, 7, 8, 9, 10, 11] w=[9] x=[] (fullness=233/0)
c :   Ready: 6 r=[7] w=[9] x=[]
c : mux wrote: 46/46
c : Accept UDP using recvfrom.
c : DNS request from ('127.0.0.1', 36237) to None: 40 bytes
c :  > channel=9 cmd=DNS_REQ len=40 (fullness=233)
c : Remaining DNS requests: 6
c : Remaining UDP channels: 0
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : Waiting: 6 r=[5, 7, 8, 9, 10, 11] w=[9] x=[] (fullness=273/0)
c :   Ready: 6 r=[] w=[9] x=[]
c : mux wrote: 48/48
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : Waiting: 6 r=[5, 7, 8, 9, 10, 11] w=[] x=[] (fullness=273/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=1 cmd=DNS_REQ len=32
 s: Incoming DNS request channel=1.
 s: DNS: sending to '108.61.10.10' (try 1)
 s: <  channel=2 cmd=TCP_CONNECT len=19
 s: Connecting to 202.108.23.152:80
 s: creating new SockWrapper (1 now exist)
 s: SW#7:202.108.23.152:80: trying connect to (u'202.108.23.152', 80)
 s: SW#7:202.108.23.152:80: connect result: [Errno 115] Operation now in progress
 s: creating new SockWrapper (2 now exist)
 s: new channel: 2
 s: <  channel=3 cmd=TCP_CONNECT len=19
 s: Connecting to 202.108.23.152:80
 s: creating new SockWrapper (3 now exist)
 s: SW#8:202.108.23.152:80: trying connect to (u'202.108.23.152', 80)
 s: SW#8:202.108.23.152:80: connect result: [Errno 115] Operation now in progress
 s: creating new SockWrapper (4 now exist)
 s: new channel: 3
 s: <  channel=4 cmd=TCP_CONNECT len=19
 s: Connecting to 202.108.23.152:80
 s: creating new SockWrapper (5 now exist)
 s: SW#9:202.108.23.152:80: trying connect to (u'202.108.23.152', 80)
 s: SW#9:202.108.23.152:80: connect result: [Errno 115] Operation now in progress
 s: creating new SockWrapper (6 now exist)
 s: new channel: 4
 s: <  channel=5 cmd=DNS_REQ len=28
 s: Incoming DNS request channel=5.
 s: DNS: sending to '108.61.10.10' (try 1)
 s: SW#7:202.108.23.152:80: trying connect to (u'202.108.23.152', 80)
 s: SW#7:202.108.23.152:80: connect result: [Errno 114] Operation already in progress
 s: SW#8:202.108.23.152:80: trying connect to (u'202.108.23.152', 80)
 s: SW#8:202.108.23.152:80: connect result: [Errno 114] Operation already in progress
 s: SW#9:202.108.23.152:80: trying connect to (u'202.108.23.152', 80)
 s: SW#9:202.108.23.152:80: connect result: [Errno 114] Operation already in progress
 s: Waiting: 6 r=[4, 6, 10] w=[7, 8, 9] x=[] (fullness=0/0)
 s:   Ready: 6 r=[4, 6, 10] w=[] x=[]
 s: <  channel=6 cmd=DNS_REQ len=47
 s: Incoming DNS request channel=6.
 s: DNS: sending to '108.61.10.10' (try 1)
 s: <  channel=7 cmd=DNS_REQ len=31
 s: Incoming DNS request channel=7.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 37, in <module>
  File "sshuttle.server", line 334, in main
  File "sshuttle.ssnet", line 583, in runonce
  File "sshuttle.ssnet", line 481, in callback
  File "sshuttle.ssnet", line 469, in handle
  File "sshuttle.ssnet", line 403, in got_packet
  File "sshuttle.server", line 293, in dns_req
  File "sshuttle.server", line 136, in __init__
  File "sshuttle.server", line 147, in try_send
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 101] Network is unreachable
c :   Ready: 6 r=[9] w=[] x=[]
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
c : read: err was: [Errno 11] Resource temporarily unavailable
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
firewall manager: undoing /etc/hosts changes.
c : fatal: server died with error code 1
c : SW#11:192.168.1.131:39974: deleting (5 remain)
c : SW'unknown':Mux#2: done writing
c :  > channel=2 cmd=TCP_EOF len=0 (fullness=273)
c : SW'unknown':Mux#2: deleting (4 remain)
c : SW#8:192.168.1.131:39970: deleting (3 remain)
c : SW'unknown':Mux#3: done writing
c :  > channel=3 cmd=TCP_EOF len=0 (fullness=273)
c : SW'unknown':Mux#3: deleting (2 remain)
c : SW#10:192.168.1.131:39972: deleting (1 remain)
c : SW'unknown':Mux#4: done writing
c :  > channel=4 cmd=TCP_EOF len=0 (fullness=273)
c : SW'unknown':Mux#4: deleting (0 remain)
```

**Comment by naclander** [comment]
What is the full command you used to call sshuttle?

**Comment by d0u9** [comment]
sshuttle --dns -vvvr username@server 0/0

**Comment by brianmay** [comment]
That looks like the server has an unreachable DNS server in its ``/etc/resolv.conf``?

**Comment by brianmay** [comment]
We could (and maybe we should) add ``ENETUNREACH`` to ``NET_ERRS`` so that the error triggers a retry using (hopefully) another server (instead of a fatal error), however it occurs to me that there might be a problem with the config on your server too.
